export type AimAttersTool = {
  name: string;
  slug: string;
  category: string;
  description: string;
  useCase: string;
  tokenTip: string;
  promptStarter: string;
  pricing: string;
  source: string;
  verifiedAt: string;
  url: string;
  tags: string[];
};

/** Curated from the visible AimAtters AI Tool DB entries; official product URLs are used for actions. */
export const aimattersTools: AimAttersTool[] = [
  { name: "10Web AI", slug: "10web-ai", category: "바이브코딩", description: "AI로 WordPress 웹사이트를 생성하고 관리하는 웹사이트 제작 도구입니다.", useCase: "웹사이트 제작·랜딩페이지", tokenTip: "사이트 목적·페이지 수·필수 섹션을 먼저 고정하고 한 번에 한 화면씩 수정하세요.", promptStarter: "10Web AI로 [사이트 목적]의 첫 화면을 만들어줘. 필수 섹션은 [목록], 톤은 [톤], 모바일 우선으로 구성해줘.", pricing: "공식 사이트 확인", source: "AimAtters AI Tool DB", verifiedAt: "2026-08-26", url: "https://10web.io/", tags: ["웹사이트", "WordPress", "바이브코딩"] },
  { name: "Colossyan", slug: "colossyan", category: "영상", description: "AI 아바타와 텍스트 기반 편집으로 교육·온보딩 영상을 제작하는 플랫폼입니다.", useCase: "교육 영상·온보딩", tokenTip: "장면마다 한 메시지만 배치하고 긴 원고는 챕터로 나눠 재생성 비용을 줄이세요.", promptStarter: "Colossyan용 교육 영상 원고를 6개 장면으로 나눠줘. 대상은 [대상], 목표는 [목표], 장면당 35단어 이내로 작성해줘.", pricing: "공식 사이트 확인", source: "AimAtters AI Tool DB", verifiedAt: "2026-08-26", url: "https://www.colossyan.com/", tags: ["아바타", "교육", "영상"] },
  { name: "Elai.io", slug: "elai-io", category: "영상", description: "텍스트를 AI 아바타 교육 영상으로 바꾸는 비디오 제작 플랫폼입니다.", useCase: "교육 콘텐츠·설명 영상", tokenTip: "공통 인트로와 아웃트로를 템플릿화하고 본문 장면만 교체하세요.", promptStarter: "Elai.io에서 [주제]를 설명하는 5분 교육 영상 구조를 장면·내레이션·화면 자막으로 나눠줘.", pricing: "공식 사이트 확인", source: "AimAtters AI Tool DB", verifiedAt: "2026-08-26", url: "https://elai.io/", tags: ["아바타", "교육", "영상"] },
  { name: "FlexClip AI", slug: "flexclip-ai", category: "영상", description: "긴 영상을 숏폼 콘텐츠로 편집하고 자막·장면 구성을 돕는 AI 영상 도구입니다.", useCase: "숏폼·영상 편집", tokenTip: "원본 영상의 핵심 타임코드와 목표 채널을 먼저 지정해 후보 장면을 줄이세요.", promptStarter: "FlexClip AI에서 [원본 주제] 영상의 30초 숏폼 3개를 제안해줘. 각 영상은 훅·핵심·CTA로 구성해줘.", pricing: "공식 사이트 확인", source: "AimAtters AI Tool DB", verifiedAt: "2026-08-26", url: "https://www.flexclip.com/", tags: ["영상 편집", "숏폼", "콘텐츠"] },
  { name: "Knowt", slug: "knowt", category: "문서·리서치", description: "노트와 학습 자료를 플래시카드와 퀴즈로 바꾸는 AI 학습 도구입니다.", useCase: "학습자료·퀴즈", tokenTip: "시험 범위와 난이도를 먼저 지정하고 자료 전체보다 필요한 챕터만 입력하세요.", promptStarter: "Knowt에서 다음 학습자료를 초급·중급·고급 플래시카드로 나누고 각 카드에 정답 근거를 붙여줘: [자료].", pricing: "공식 사이트 확인", source: "AimAtters AI Tool DB", verifiedAt: "2026-08-26", url: "https://knowt.com/", tags: ["학습", "퀴즈", "문서"] },
  { name: "Quizgecko", slug: "quizgecko", category: "문서·리서치", description: "학습 자료에서 퀴즈와 시험 문제를 자동으로 생성하는 AI 도구입니다.", useCase: "퀴즈·평가 문항", tokenTip: "문항 수·문제 유형·정답 근거를 고정해 불필요한 재생성을 줄이세요.", promptStarter: "Quizgecko용 평가 문항을 만들어줘. 대상은 [대상], 문항 수는 10개, 유형은 객관식 6개와 서술형 4개로 해줘.", pricing: "공식 사이트 확인", source: "AimAtters AI Tool DB", verifiedAt: "2026-08-26", url: "https://quizgecko.com/", tags: ["학습", "퀴즈", "교육"] },
  { name: "Mindgrasp", slug: "mindgrasp", category: "문서·리서치", description: "강의와 문서를 요약하고 질문에 답하는 AI 학습 보조 도구입니다.", useCase: "강의·문서 요약", tokenTip: "요약 목적과 원하는 길이를 먼저 지정하고 후속 질문은 한 주제씩 묻세요.", promptStarter: "Mindgrasp에서 [자료]를 시험 대비용으로 요약해줘. 핵심 개념·예시·헷갈리는 점·복습 질문 순서로 정리해줘.", pricing: "공식 사이트 확인", source: "AimAtters AI Tool DB", verifiedAt: "2026-08-26", url: "https://mindgrasp.ai/", tags: ["학습", "문서", "요약"] },
  { name: "StudyFetch", slug: "studyfetch", category: "문서·리서치", description: "수업 자료를 AI 노트·퀴즈·플래시카드로 변환하는 학습 플랫폼입니다.", useCase: "수업자료·시험준비", tokenTip: "자료를 과목·주차별로 나눠 업로드하고 원하는 산출물만 먼저 생성하세요.", promptStarter: "StudyFetch에서 [과목] 자료를 주차별 복습 노트와 플래시카드로 정리해줘. 시험에 나올 가능성이 높은 개념을 표시해줘.", pricing: "공식 사이트 확인", source: "AimAtters AI Tool DB", verifiedAt: "2026-08-26", url: "https://www.studyfetch.com/", tags: ["학습", "플래시카드", "문서"] },
  { name: "Reclaim.ai", slug: "reclaim-ai", category: "업무·자동화", description: "할 일과 반복 일정을 캘린더 빈 시간에 자동으로 배치하는 일정 관리 도구입니다.", useCase: "일정·집중시간·업무계획", tokenTip: "업무 우선순위·소요시간·마감만 정확히 입력하고 세부 설명은 캘린더 메모로 분리하세요.", promptStarter: "Reclaim.ai에서 [업무 목록]을 이번 주 일정에 배치해줘. 우선순위는 [기준], 집중 시간은 하루 [시간]으로 보호해줘.", pricing: "공식 사이트 확인", source: "AimAtters AI Tool DB", verifiedAt: "2026-08-26", url: "https://reclaim.ai/", tags: ["일정", "생산성", "자동화"] },
  { name: "Sembly AI", slug: "sembly-ai", category: "회의·전사", description: "회의 내용을 기록하고 실행 가능한 업무와 요약으로 정리하는 AI 회의 비서입니다.", useCase: "회의록·액션아이템", tokenTip: "회의 목적과 참석자 역할을 미리 설정해 요약에서 필요한 결정과 담당자를 우선 추출하세요.", promptStarter: "Sembly AI 회의록에서 결정사항·담당자·마감일·미해결 질문만 표로 정리해줘.", pricing: "공식 사이트 확인", source: "AimAtters AI Tool DB", verifiedAt: "2026-08-26", url: "https://www.sembly.ai/", tags: ["회의", "전사", "업무"] },
  { name: "Notta", slug: "notta", category: "회의·전사", description: "회의·인터뷰·강의를 전사하고 번역·요약하는 AI 전사 도구입니다.", useCase: "전사·번역·회의 요약", tokenTip: "언어와 화자 수를 먼저 지정하고 전체 재요약보다 필요한 구간만 후속 처리하세요.", promptStarter: "Notta 전사본에서 발언자별 핵심 주장과 후속 할 일을 한국어로 요약해줘. 불명확한 부분은 [확인 필요]로 표시해줘.", pricing: "공식 사이트 확인", source: "AimAtters AI Tool DB", verifiedAt: "2026-08-26", url: "https://www.notta.ai/", tags: ["회의", "전사", "번역"] },
  { name: "Avoma", slug: "avoma", category: "회의·전사", description: "회의 요약과 세일즈 코칭을 지원하는 AI 미팅 인텔리전스 플랫폼입니다.", useCase: "세일즈 회의·코칭", tokenTip: "회의 유형별 템플릿을 고정해 매번 전체 녹취를 같은 방식으로 분석하지 않도록 하세요.", promptStarter: "Avoma에서 이 세일즈 미팅을 니즈·반대 의견·다음 단계·리스크 기준으로 코칭해줘: [전사].", pricing: "공식 사이트 확인", source: "AimAtters AI Tool DB", verifiedAt: "2026-08-26", url: "https://www.avoma.com/", tags: ["회의", "세일즈", "코칭"] },
  { name: "TurboScribe", slug: "turboscribe", category: "회의·전사", description: "대용량 음성·영상 파일을 텍스트로 변환하는 AI 전사 서비스입니다.", useCase: "대용량 전사·자막", tokenTip: "긴 파일은 필요한 구간을 먼저 분리하고 언어·출력 형식을 미리 지정하세요.", promptStarter: "TurboScribe 전사본에서 60초 단위 핵심 구간과 자막용 문장을 추출해줘.", pricing: "공식 사이트 확인", source: "AimAtters AI Tool DB", verifiedAt: "2026-08-26", url: "https://turboscribe.ai/", tags: ["전사", "자막", "음성"] },
  { name: "tl;dv", slug: "tl-dv", category: "회의·전사", description: "화상회의를 녹화·전사하고 핵심 내용을 요약하는 회의 비서입니다.", useCase: "화상회의·회의 검색", tokenTip: "회의 아젠다와 원하는 요약 항목을 미리 설정해 전체 녹취 재처리를 줄이세요.", promptStarter: "tl;dv에서 회의별 결정사항과 담당자 액션을 팀 공유용 5줄 요약으로 만들어줘.", pricing: "공식 사이트 확인", source: "AimAtters AI Tool DB", verifiedAt: "2026-08-26", url: "https://www.tldv.io/", tags: ["회의", "전사", "요약"] },
  { name: "Moises", slug: "moises", category: "음성·음악", description: "보컬·악기 분리와 음악 연습을 지원하는 AI 음악 도구입니다.", useCase: "음악 연습·트랙 분리", tokenTip: "필요한 스템만 선택하고 전체 믹스를 반복 업로드하지 않도록 원본을 보관하세요.", promptStarter: "Moises에서 [곡]을 보컬·드럼·베이스·기타로 분리하고 [악기] 연습용 루프를 구성해줘.", pricing: "공식 사이트 확인", source: "AimAtters AI Tool DB", verifiedAt: "2026-08-26", url: "https://moises.ai/", tags: ["음악", "오디오", "연습"] },
  { name: "Sonix", slug: "sonix", category: "회의·전사", description: "음성·영상 파일을 텍스트로 전사하고 번역하는 AI 서비스입니다.", useCase: "전사·번역·자막", tokenTip: "목표 언어와 자막 형식을 먼저 정하고 필요한 구간만 교정하세요.", promptStarter: "Sonix 전사본을 [언어] 자막용으로 다듬어줘. 화자 구분과 타임코드는 유지해줘.", pricing: "공식 사이트 확인", source: "AimAtters AI Tool DB", verifiedAt: "2026-08-26", url: "https://sonix.ai/", tags: ["전사", "번역", "자막"] },
  { name: "Kits AI", slug: "kits-ai", category: "음성·음악", description: "보컬 변환과 음성 클로닝을 지원하는 음악 제작용 AI 보이스 도구입니다.", useCase: "보컬·음성 제작", tokenTip: "짧은 프레이즈로 먼저 테스트하고 권리·동의가 확인된 음성만 사용하세요.", promptStarter: "Kits AI에서 [곡 분위기]에 맞는 보컬 프레이즈를 설계해줘. 음역·템포·발음 주의점을 함께 적어줘.", pricing: "공식 사이트 확인", source: "AimAtters AI Tool DB", verifiedAt: "2026-08-26", url: "https://www.kits.ai/", tags: ["음성", "음악", "보컬"] },
  { name: "Cleanvoice AI", slug: "cleanvoice-ai", category: "음성·음악", description: "팟캐스트의 노이즈와 말버릇을 자동으로 정리하는 AI 오디오 편집 도구입니다.", useCase: "팟캐스트·오디오 편집", tokenTip: "원본 파일을 보관하고 제거 강도를 낮게 시작해 자연스러운 결과를 우선 확인하세요.", promptStarter: "Cleanvoice AI에서 팟캐스트의 반복어·긴 침묵·배경 노이즈를 자연스럽게 정리해줘. 말투와 의미는 보존해줘.", pricing: "공식 사이트 확인", source: "AimAtters AI Tool DB", verifiedAt: "2026-08-26", url: "https://cleanvoice.ai/", tags: ["오디오", "팟캐스트", "편집"] },
  { name: "Jamie AI", slug: "jamie-ai", category: "회의·전사", description: "회의 봇 없이 회의 내용을 기록하고 요약하는 AI 회의 노트 도구입니다.", useCase: "회의록·액션아이템", tokenTip: "회의 목적과 원하는 산출물만 먼저 지정하고 전체 녹취 재요약은 피하세요.", promptStarter: "Jamie AI 회의 노트에서 결정사항·담당자·마감일만 추출해줘.", pricing: "공식 사이트 확인", source: "AimAtters AI Tool DB", verifiedAt: "2026-08-26", url: "https://www.meetjamie.ai/", tags: ["회의", "노트", "업무"] },
  { name: "Tactiq", slug: "tactiq", category: "회의·전사", description: "화상회의 중 녹취와 요약을 실시간으로 정리하는 AI 회의 노트 도구입니다.", useCase: "회의 전사·실시간 요약", tokenTip: "회의 유형별 템플릿을 만들고 필요한 요약 필드만 활성화하세요.", promptStarter: "Tactiq에서 이 회의의 핵심 논점과 다음 행동을 팀 공유용으로 정리해줘.", pricing: "공식 사이트 확인", source: "AimAtters AI Tool DB", verifiedAt: "2026-08-26", url: "https://tactiq.io/", tags: ["회의", "전사", "요약"] },
  { name: "Fathom", slug: "fathom", category: "회의·전사", description: "화상회의를 녹화·전사하고 핵심 내용을 정리하는 AI 회의 비서입니다.", useCase: "회의 녹화·요약", tokenTip: "회의 템플릿과 후속 메일 형식을 미리 정하면 재가공을 줄일 수 있습니다.", promptStarter: "Fathom 회의 요약에서 고객 니즈·우려·후속 약속을 분리해줘.", pricing: "공식 사이트 확인", source: "AimAtters AI Tool DB", verifiedAt: "2026-08-26", url: "https://fathom.video/", tags: ["회의", "전사", "세일즈"] },
  { name: "Mindtrip", slug: "mindtrip", category: "리서치·계획", description: "여행 일정과 장소 탐색을 대화형으로 돕는 AI 여행 계획 플랫폼입니다.", useCase: "여행 계획·장소 탐색", tokenTip: "여행 기간·예산·이동수단을 먼저 고정하고 추천 후보 수를 제한하세요.", promptStarter: "Mindtrip에서 [기간] 동안 [예산]으로 [목적지] 여행 일정을 이동시간까지 고려해 짜줘.", pricing: "공식 사이트 확인", source: "AimAtters AI Tool DB", verifiedAt: "2026-08-26", url: "https://mindtrip.ai/", tags: ["여행", "계획", "검색"] },
  { name: "Layla AI", slug: "layla-ai", category: "리서치·계획", description: "여행 날짜·목적지·예산을 바탕으로 맞춤 일정을 설계하는 AI 여행 플래너입니다.", useCase: "여행 일정·예약 탐색", tokenTip: "필수 조건과 선호 조건을 분리해 대안을 빠르게 비교하세요.", promptStarter: "Layla AI에서 [목적지]를 [여행 스타일]로 계획해줘. 필수 조건은 [조건]이야.", pricing: "공식 사이트 확인", source: "AimAtters AI Tool DB", verifiedAt: "2026-08-26", url: "https://layla.ai/", tags: ["여행", "계획", "추천"] },
  { name: "Dzine AI", slug: "dzine-ai", category: "이미지·디자인", description: "이미지 생성과 디자인 편집을 정밀하게 제어하는 AI 디자인 스튜디오입니다.", useCase: "이미지 생성·편집", tokenTip: "스타일·구도·변경 영역을 분리해 부분 수정부터 진행하세요.", promptStarter: "Dzine AI에서 [제품]을 [스타일]의 광고 이미지로 만들고 배경과 조명만 3가지로 변형해줘.", pricing: "공식 사이트 확인", source: "AimAtters AI Tool DB", verifiedAt: "2026-08-26", url: "https://www.dzine.ai/", tags: ["이미지", "디자인", "편집"] },
  { name: "LightX", slug: "lightx", category: "이미지·디자인", description: "사진·영상 편집과 AI 디자인 기능을 한곳에서 제공하는 크리에이티브 도구입니다.", useCase: "사진·영상 편집", tokenTip: "원본과 결과물을 분리하고 필요한 편집 기능만 순서대로 적용하세요.", promptStarter: "LightX에서 [사진]의 배경을 [분위기]로 바꾸고 피사체의 형태와 색은 유지해줘.", pricing: "공식 사이트 확인", source: "AimAtters AI Tool DB", verifiedAt: "2026-08-26", url: "https://www.lightxeditor.com/", tags: ["이미지", "영상", "편집"] },
  { name: "PostNitro", slug: "postnitro", category: "마케팅·SNS", description: "SNS 캐러셀 콘텐츠를 만들고 예약 발행하는 소셜미디어 디자인 도구입니다.", useCase: "SNS 캐러셀·예약 발행", tokenTip: "채널·슬라이드 수·CTA를 먼저 정해 불필요한 디자인 변형을 줄이세요.", promptStarter: "PostNitro에서 [주제]를 7장 SNS 캐러셀로 만들어줘. 첫 장은 훅, 마지막은 CTA로 구성해줘.", pricing: "공식 사이트 확인", source: "AimAtters AI Tool DB", verifiedAt: "2026-08-26", url: "https://postnitro.ai/", tags: ["SNS", "캐러셀", "마케팅"] },
  { name: "CreatorKit", slug: "creatorkit", category: "마케팅·SNS", description: "제품 사진과 마케팅 영상을 빠르게 제작하는 AI 이커머스 콘텐츠 도구입니다.", useCase: "제품 이미지·광고 콘텐츠", tokenTip: "제품 특징과 금지 변경사항을 명시해 재생성을 줄이세요.", promptStarter: "CreatorKit에서 [제품]의 이커머스 광고 이미지 3종을 만들어줘. 제품 로고와 형태는 보존해줘.", pricing: "공식 사이트 확인", source: "AimAtters AI Tool DB", verifiedAt: "2026-08-26", url: "https://creatorkit.com/", tags: ["이커머스", "제품사진", "마케팅"] },
  { name: "Pebblely", slug: "pebblely", category: "이미지·디자인", description: "제품 사진을 마케팅용 배경과 장면으로 바꾸는 AI 제품 촬영 도구입니다.", useCase: "제품 사진·배경 생성", tokenTip: "제품의 보존 영역과 원하는 배경 수를 먼저 고정하세요.", promptStarter: "Pebblely에서 [제품 사진]을 [브랜드 톤]의 스튜디오 장면으로 바꿔줘. 제품 비율은 유지해줘.", pricing: "공식 사이트 확인", source: "AimAtters AI Tool DB", verifiedAt: "2026-08-26", url: "https://pebblely.com/", tags: ["제품사진", "이커머스", "이미지"] },
  { name: "FeedHive", slug: "feedhive", category: "마케팅·SNS", description: "소셜미디어 콘텐츠 제작과 예약 발행을 지원하는 AI 운영 플랫폼입니다.", useCase: "SNS 운영·예약 발행", tokenTip: "콘텐츠 기둥과 게시 빈도를 먼저 설정해 매번 전략을 다시 생성하지 마세요.", promptStarter: "FeedHive용 한 달 콘텐츠 캘린더를 만들어줘. 주제는 [주제], 채널은 [채널], 게시 빈도는 [빈도]야.", pricing: "공식 사이트 확인", source: "AimAtters AI Tool DB", verifiedAt: "2026-08-26", url: "https://www.feedhive.com/", tags: ["SNS", "예약", "콘텐츠"] },
  { name: "Taja AI", slug: "taja-ai", category: "마케팅·SNS", description: "유튜브 영상을 쇼츠·블로그·소셜 콘텐츠로 확장하는 AI 콘텐츠 도구입니다.", useCase: "영상 재활용·SEO 콘텐츠", tokenTip: "원본 영상의 핵심 메시지와 목표 채널을 지정해 파생물 수를 제한하세요.", promptStarter: "Taja AI에서 이 영상의 핵심 주제 3개를 뽑아 쇼츠·블로그·SNS 문구로 변환해줘: [링크].", pricing: "공식 사이트 확인", source: "AimAtters AI Tool DB", verifiedAt: "2026-08-26", url: "https://www.taja.ai/", tags: ["유튜브", "SEO", "콘텐츠"] },
  { name: "Pencil", slug: "pencil", category: "마케팅·SNS", description: "광고 크리에이티브 제작과 성과 예측을 지원하는 AI 마케팅 플랫폼입니다.", useCase: "광고 소재·크리에이티브", tokenTip: "제품·타깃·캠페인 목표를 고정하고 변형 수만 제한해 테스트하세요.", promptStarter: "Pencil에서 [제품]의 [타깃]용 광고 크리에이티브 3안을 훅·비주얼·CTA로 제안해줘.", pricing: "공식 사이트 확인", source: "AimAtters AI Tool DB", verifiedAt: "2026-08-26", url: "https://www.trypencil.com/", tags: ["광고", "마케팅", "크리에이티브"] },
  { name: "Quso.ai", slug: "quso-ai", category: "영상", description: "긴 영상을 숏폼으로 바꾸고 소셜 게시까지 돕는 AI 영상 마케팅 도구입니다.", useCase: "영상 클리핑·SNS 게시", tokenTip: "목표 채널별 길이와 화면비를 먼저 고정하세요.", promptStarter: "Quso.ai에서 [영상]의 핵심 장면을 30초 쇼츠 3개로 만들고 각각의 CTA를 적어줘.", pricing: "공식 사이트 확인", source: "AimAtters AI Tool DB", verifiedAt: "2026-08-26", url: "https://quso.ai/", tags: ["숏폼", "영상", "SNS"] },
  { name: "Revid.ai", slug: "revid-ai", category: "영상", description: "프롬프트·스크립트·링크를 숏폼 영상으로 바꾸는 AI 영상 생성 도구입니다.", useCase: "숏폼 영상 생성", tokenTip: "영상 길이·음성·자막 스타일을 먼저 선택하고 변형을 최소화하세요.", promptStarter: "Revid.ai에서 [주제]를 45초 세로 영상으로 만들어줘. 훅·근거·CTA와 자막을 포함해줘.", pricing: "공식 사이트 확인", source: "AimAtters AI Tool DB", verifiedAt: "2026-08-26", url: "https://www.revid.ai/", tags: ["숏폼", "영상", "스크립트"] },
  { name: "Captions", slug: "captions", category: "영상", description: "AI 영상 편집·자막·더빙을 자동화하는 크리에이터용 도구입니다.", useCase: "자막·더빙·영상 편집", tokenTip: "언어와 자막 스타일을 고정한 뒤 필요한 장면만 재편집하세요.", promptStarter: "Captions에서 이 영상의 한국어 자막을 만들고 핵심 문장만 강조해줘: [영상].", pricing: "공식 사이트 확인", source: "AimAtters AI Tool DB", verifiedAt: "2026-08-26", url: "https://www.captions.ai/", tags: ["자막", "더빙", "영상"] },
  { name: "Munch", slug: "munch", category: "영상", description: "긴 영상을 소셜미디어용 콘텐츠로 재가공하는 AI 영상 도구입니다.", useCase: "영상 재활용·클립", tokenTip: "타깃 채널과 시청자 관심사를 지정해 후보 클립 수를 줄이세요.", promptStarter: "Munch에서 이 긴 영상의 핵심 클립 5개를 만들고 각 클립의 제목과 채널별 설명을 작성해줘.", pricing: "공식 사이트 확인", source: "AimAtters AI Tool DB", verifiedAt: "2026-08-26", url: "https://www.getmunch.com/", tags: ["영상", "클립", "SNS"] },
  { name: "Crayo", slug: "crayo", category: "영상", description: "AI 쇼츠와 게임플레이 영상을 빠르게 제작하는 숏폼 도구입니다.", useCase: "쇼츠·게임 영상", tokenTip: "영상 형식과 목표 길이를 고정하고 장면 변형은 한 번에 비교하세요.", promptStarter: "Crayo에서 [주제] 쇼츠를 30초 분량으로 구성해줘. 첫 3초 훅과 자막을 포함해줘.", pricing: "공식 사이트 확인", source: "AimAtters AI Tool DB", verifiedAt: "2026-08-26", url: "https://crayo.ai/", tags: ["쇼츠", "영상", "게임"] },
  { name: "SendShort", slug: "sendshort", category: "영상", description: "숏폼 영상을 생성하고 예약 발행하는 AI 쇼츠 제작 도구입니다.", useCase: "쇼츠 제작·예약", tokenTip: "게시 채널별 비율과 길이를 템플릿으로 고정하세요.", promptStarter: "SendShort에서 [주제]를 TikTok·Reels·Shorts용으로 각각 최적화해줘.", pricing: "공식 사이트 확인", source: "AimAtters AI Tool DB", verifiedAt: "2026-08-26", url: "https://sendshort.ai/", tags: ["쇼츠", "예약", "SNS"] },
  { name: "Minvo", slug: "minvo", category: "영상", description: "긴 영상을 숏폼·이미지·텍스트 콘텐츠로 재활용하는 AI 편집 도구입니다.", useCase: "콘텐츠 재활용·편집", tokenTip: "원본의 핵심 주제와 파생 콘텐츠 수를 먼저 정하세요.", promptStarter: "Minvo에서 이 영상을 쇼츠 3개와 게시물 요약 3개로 재활용해줘: [영상].", pricing: "공식 사이트 확인", source: "AimAtters AI Tool DB", verifiedAt: "2026-08-26", url: "https://minvo.pro/", tags: ["영상", "재활용", "콘텐츠"] },
  { name: "Klap", slug: "klap", category: "영상", description: "긴 유튜브 영상을 쇼츠·릴스·틱톡 클립으로 변환하는 AI 도구입니다.", useCase: "영상 클리핑·숏폼", tokenTip: "원본 언어와 타깃 채널을 입력해 자막과 화면비 재작업을 줄이세요.", promptStarter: "Klap에서 [유튜브 링크]의 가장 이해하기 쉬운 장면 5개를 세로 클립으로 만들어줘.", pricing: "공식 사이트 확인", source: "AimAtters AI Tool DB", verifiedAt: "2026-08-26", url: "https://klap.app/", tags: ["유튜브", "숏폼", "클립"] },
  { name: "Vizard", slug: "vizard", category: "영상", description: "긴 영상을 숏폼 클립으로 자동 변환하는 AI 영상 편집 도구입니다.", useCase: "영상 클립·자막", tokenTip: "클립 수와 목표 길이를 제한하고 가장 중요한 구간만 교정하세요.", promptStarter: "Vizard에서 이 인터뷰 영상의 인사이트 클립 4개를 골라 제목과 자막을 만들어줘: [영상].", pricing: "공식 사이트 확인", source: "AimAtters AI Tool DB", verifiedAt: "2026-08-26", url: "https://vizard.ai/", tags: ["영상", "클립", "자막"] },
  { name: "Submagic", slug: "submagic", category: "영상", description: "숏폼 영상의 자막과 편집을 빠르게 자동화하는 AI 도구입니다.", useCase: "숏폼 자막·편집", tokenTip: "자막 템플릿과 강조 단어 규칙을 고정해 반복 교정을 줄이세요.", promptStarter: "Submagic에서 이 쇼츠의 핵심 단어만 강조한 자막을 만들고 화면 전환 타이밍을 제안해줘: [영상].", pricing: "공식 사이트 확인", source: "AimAtters AI Tool DB", verifiedAt: "2026-08-26", url: "https://www.submagic.co/", tags: ["자막", "숏폼", "편집"] },
  { name: "LALAL.AI", slug: "lalal-ai", category: "음성·음악", description: "보컬과 악기를 분리하는 AI 오디오 스템 분리 도구입니다.", useCase: "보컬·악기 분리", tokenTip: "필요한 스템만 선택하고 원본 오디오를 중복 처리하지 마세요.", promptStarter: "LALAL.AI에서 [곡]의 보컬과 반주를 분리해 연습용 파일로 정리해줘.", pricing: "공식 사이트 확인", source: "AimAtters AI Tool DB", verifiedAt: "2026-08-26", url: "https://www.lalal.ai/", tags: ["오디오", "음악", "스템"] },
  { name: "PLAUD AI", slug: "plaud-ai", category: "회의·전사", description: "회의와 음성 파일을 기록하고 요약하는 AI 노트 테이커입니다.", useCase: "회의·음성 기록", tokenTip: "녹음 전 회의 제목과 참석자 정보를 고정해 후처리 분류를 줄이세요.", promptStarter: "PLAUD AI에서 이 녹음의 의사결정·액션·보류 질문을 표로 정리해줘: [녹취].", pricing: "공식 사이트 확인", source: "AimAtters AI Tool DB", verifiedAt: "2026-08-26", url: "https://www.plaud.ai/", tags: ["회의", "녹음", "요약"] },
  { name: "Spline AI", slug: "spline-ai", category: "3D·프로토타이핑", description: "텍스트와 이미지를 3D 오브젝트로 바꾸는 AI 3D 디자인 도구입니다.", useCase: "3D 오브젝트·웹 인터랙션", tokenTip: "오브젝트 수와 재질 수를 제한해 초안부터 가볍게 확인하세요.", promptStarter: "Spline AI에서 [오브젝트]를 웹 히어로용 3D 모델로 설계해줘. 재질은 [재질], 색은 [색]이야.", pricing: "공식 사이트 확인", source: "AimAtters AI Tool DB", verifiedAt: "2026-08-26", url: "https://spline.design/ai", tags: ["3D", "디자인", "웹"] },
  { name: "Kaedim", slug: "kaedim", category: "3D·프로토타이핑", description: "이미지와 콘셉트를 제작용 3D 에셋으로 바꾸는 AI 플랫폼입니다.", useCase: "3D 에셋·게임 제작", tokenTip: "참조 이미지와 필요한 폴리곤 수준을 먼저 고정해 재작업을 줄이세요.", promptStarter: "Kaedim에서 이 콘셉트를 게임용 3D 에셋으로 변환해줘. 스타일은 [스타일], 용도는 [용도]야.", pricing: "공식 사이트 확인", source: "AimAtters AI Tool DB", verifiedAt: "2026-08-26", url: "https://www.kaedim3d.com/", tags: ["3D", "게임", "에셋"] },
  { name: "Dubverse", slug: "dubverse", category: "영상", description: "AI 더빙과 자막으로 영상을 여러 언어로 현지화하는 플랫폼입니다.", useCase: "영상 더빙·현지화", tokenTip: "원본 언어·목표 언어·화자 수를 먼저 지정하고 필요한 언어만 생성하세요.", promptStarter: "Dubverse에서 이 영상을 [목표 언어]로 더빙해줘. 고유명사와 브랜드 용어는 원문 표기를 유지해줘.", pricing: "공식 사이트 확인", source: "AimAtters AI Tool DB", verifiedAt: "2026-08-26", url: "https://dubverse.ai/", tags: ["더빙", "번역", "영상"] },
  { name: "Rask AI", slug: "rask-ai", category: "영상", description: "영상을 여러 언어로 번역·더빙하는 AI 로컬라이제이션 도구입니다.", useCase: "영상 번역·더빙", tokenTip: "필요한 목표 언어와 화자 수를 제한하고 용어집을 재사용하세요.", promptStarter: "Rask AI에서 이 영상을 [언어]로 번역·더빙해줘. 용어집은 [용어]를 따르고 화자 톤은 유지해줘.", pricing: "공식 사이트 확인", source: "AimAtters AI Tool DB", verifiedAt: "2026-08-26", url: "https://www.rask.ai/", tags: ["번역", "더빙", "현지화"] },
  { name: "Morph Studio", slug: "morph-studio", category: "영상", description: "프롬프트와 오픈 캔버스로 이미지·비디오를 만드는 생성 도구입니다.", useCase: "영상 생성·스토리보드", tokenTip: "장면·카메라·스타일을 분리한 짧은 프롬프트로 먼저 테스트하세요.", promptStarter: "Morph Studio에서 [장면]을 [카메라 움직임]으로 5초 영상화해줘. 스타일은 [스타일]이야.", pricing: "공식 사이트 확인", source: "AimAtters AI Tool DB", verifiedAt: "2026-08-26", url: "https://www.morphstudio.com/", tags: ["영상 생성", "이미지", "캔버스"] },
  { name: "Omi", slug: "omi", category: "회의·전사", description: "일상 대화와 회의를 검색 가능한 기억으로 바꾸는 AI 웨어러블 노트입니다.", useCase: "개인 기록·회의 기억", tokenTip: "기록 목적과 보관 범위를 정하고 민감한 대화는 녹음하지 마세요.", promptStarter: "Omi 기록에서 [주제]와 관련된 대화만 찾아 시간순 요약으로 정리해줘.", pricing: "공식 사이트 확인", source: "AimAtters AI Tool DB", verifiedAt: "2026-08-26", url: "https://www.omi.me/", tags: ["기록", "웨어러블", "검색"] },
  { name: "Genmo", slug: "genmo", category: "영상", description: "텍스트 아이디어를 영상으로 바꾸는 오픈소스 AI 비디오 플랫폼입니다.", useCase: "텍스트·영상 생성", tokenTip: "짧은 장면 단위로 생성하고 시퀀스 연결은 후편집에서 처리하세요.", promptStarter: "Genmo에서 [아이디어]를 5초 시네마틱 장면으로 만들어줘. 피사체·움직임·조명을 분리해줘.", pricing: "공식 사이트 확인", source: "AimAtters AI Tool DB", verifiedAt: "2026-08-26", url: "https://www.genmo.ai/", tags: ["영상 생성", "오픈소스", "콘텐츠"] },
  { name: "Rosebud AI", slug: "rosebud-ai", category: "게임·인터랙션", description: "프롬프트로 게임과 인터랙티브 스토리를 만드는 AI 제작 도구입니다.", useCase: "게임 프로토타입·인터랙티브", tokenTip: "게임 규칙과 화면 하나를 먼저 고정하고 기능을 작은 단위로 확장하세요.", promptStarter: "Rosebud AI에서 [장르] 게임의 한 화면 프로토타입을 만들어줘. 규칙은 [규칙], 승리 조건은 [조건]이야.", pricing: "공식 사이트 확인", source: "AimAtters AI Tool DB", verifiedAt: "2026-08-26", url: "https://rosebud.ai/", tags: ["게임", "프로토타입", "스토리"] },
  { name: "Kaiber", slug: "kaiber", category: "영상", description: "음악과 이미지를 연결해 AI 비주얼 영상을 만드는 도구입니다.", useCase: "뮤직비디오·비주얼", tokenTip: "음악 길이와 장면 수를 먼저 정하고 스타일 전환을 제한하세요.", promptStarter: "Kaiber에서 [음악 분위기]에 맞는 4장면 비주얼 영상을 구성해줘. 색과 전환 규칙을 유지해줘.", pricing: "공식 사이트 확인", source: "AimAtters AI Tool DB", verifiedAt: "2026-08-26", url: "https://kaiber.ai/", tags: ["음악", "영상", "비주얼"] },
  { name: "Kive", slug: "kive", category: "이미지·디자인", description: "브랜드 제품 사진과 비주얼 자산을 관리·제작하는 AI 플랫폼입니다.", useCase: "브랜드 비주얼·제품 이미지", tokenTip: "브랜드 가이드와 참조 이미지를 먼저 고정해 일관성 재수정을 줄이세요.", promptStarter: "Kive에서 [제품]의 브랜드 비주얼 보드와 캠페인 이미지 방향 3가지를 구성해줘.", pricing: "공식 사이트 확인", source: "AimAtters AI Tool DB", verifiedAt: "2026-08-26", url: "https://kive.ai/", tags: ["브랜드", "이미지", "에셋"] },
  { name: "Fyxer", slug: "fyxer", category: "업무·자동화", description: "이메일 답장과 회의 노트를 정리하는 AI 비서입니다.", useCase: "이메일·회의 후속", tokenTip: "답장 톤·길이·금지 표현을 설정해 수정 횟수를 줄이세요.", promptStarter: "Fyxer에서 이 이메일에 정중하고 간결한 답장을 작성해줘. 다음 행동과 기한을 명확히 해줘: [메일].", pricing: "공식 사이트 확인", source: "AimAtters AI Tool DB", verifiedAt: "2026-08-26", url: "https://fyxer.com/", tags: ["이메일", "회의", "비서"] },
  { name: "JoggAI", slug: "joggai", category: "영상", description: "AI 아바타로 숏폼과 광고 영상을 만드는 영상 생성 도구입니다.", useCase: "아바타 광고·숏폼", tokenTip: "스크립트·아바타·화면비를 먼저 정하고 장면 변형을 제한하세요.", promptStarter: "JoggAI에서 [제품]을 소개하는 30초 광고 스크립트를 아바타 내레이션용으로 만들어줘.", pricing: "공식 사이트 확인", source: "AimAtters AI Tool DB", verifiedAt: "2026-08-26", url: "https://www.jogg.ai/", tags: ["아바타", "광고", "영상"] },
  { name: "Creatify AI", slug: "creatify-ai", category: "마케팅·SNS", description: "제품 URL만으로 광고 영상을 제작하는 AI 광고 플랫폼입니다.", useCase: "제품 광고 영상", tokenTip: "제품의 핵심 혜택과 타깃 고객을 먼저 입력해 불필요한 카피 변형을 줄이세요.", promptStarter: "Creatify AI에서 이 제품 URL의 핵심 혜택을 20초 광고 영상 스크립트로 바꿔줘: [URL].", pricing: "공식 사이트 확인", source: "AimAtters AI Tool DB", verifiedAt: "2026-08-26", url: "https://creatify.ai/", tags: ["광고", "제품", "영상"] },
  { name: "Arcads", slug: "arcads", category: "마케팅·SNS", description: "AI 배우를 활용해 UGC 광고 영상을 제작하는 플랫폼입니다.", useCase: "UGC 광고·크리에이티브", tokenTip: "광고 주장과 금지 표현을 먼저 검토하고 배우·장면 수를 제한하세요.", promptStarter: "Arcads용 UGC 광고 스크립트를 작성해줘. 제품은 [제품], 타깃은 [타깃], 핵심 주장은 [주장]이야.", pricing: "공식 사이트 확인", source: "AimAtters AI Tool DB", verifiedAt: "2026-08-26", url: "https://www.arcads.ai/", tags: ["UGC", "광고", "영상"] },
  { name: "Mureka AI", slug: "mureka-ai", category: "음성·음악", description: "텍스트 아이디어를 음악으로 바꾸는 AI 음악 생성 플랫폼입니다.", useCase: "음악·배경음 생성", tokenTip: "장르·템포·길이·악기만 먼저 지정해 여러 변형 생성을 줄이세요.", promptStarter: "Mureka AI에서 [장면]에 맞는 [장르] 배경음악을 만들어줘. 템포는 [BPM], 길이는 [길이]야.", pricing: "공식 사이트 확인", source: "AimAtters AI Tool DB", verifiedAt: "2026-08-26", url: "https://www.mureka.ai/", tags: ["음악", "생성", "배경음"] },
  { name: "Katalist", slug: "katalist", category: "영상", description: "아이디어를 스토리보드와 영상으로 바꾸는 AI 비주얼 스토리텔링 플랫폼입니다.", useCase: "스토리보드·영상 기획", tokenTip: "캐릭터·장소·화면비를 먼저 고정해 장면 간 일관성을 유지하세요.", promptStarter: "Katalist에서 [아이디어]를 8컷 스토리보드로 만들고 각 컷의 화면·대사·전환을 적어줘.", pricing: "공식 사이트 확인", source: "AimAtters AI Tool DB", verifiedAt: "2026-08-26", url: "https://www.katalist.ai/", tags: ["스토리보드", "영상", "기획"] },
  { name: "Lovart AI", slug: "lovart-ai", category: "이미지·디자인", description: "몇 분 안에 디자인 결과물을 만드는 AI 디자인 에이전트입니다.", useCase: "브랜드 디자인·캠페인", tokenTip: "산출물 종류·브랜드 규칙·필수 문구를 먼저 고정하세요.", promptStarter: "Lovart AI에서 [브랜드]의 [산출물]을 만들어줘. 색상·폰트·필수 문구는 [가이드]를 따라줘.", pricing: "공식 사이트 확인", source: "AimAtters AI Tool DB", verifiedAt: "2026-08-26", url: "https://www.lovart.ai/", tags: ["디자인", "에이전트", "브랜드"] },
  { name: "PixVerse", slug: "pixverse", category: "영상", description: "텍스트와 이미지를 숏폼·광고 영상으로 만드는 생성형 AI 영상 플랫폼입니다.", useCase: "숏폼·광고 영상 생성", tokenTip: "장면 길이와 카메라 움직임을 먼저 고정하고 짧은 클립부터 비교하세요.", promptStarter: "PixVerse에서 [제품]을 [장면] 속 5초 광고 영상으로 만들어줘. 카메라는 [움직임], 비율은 세로야.", pricing: "공식 사이트 확인", source: "AimAtters AI Tool DB", verifiedAt: "2026-08-26", url: "https://pixverse.ai/", tags: ["영상", "광고", "생성"] },
  { name: "ElevenLabs Music", slug: "elevenlabs-music", category: "음성·음악", description: "보컬과 편곡을 제어해 음악을 만드는 AI 음악 생성 기능입니다.", useCase: "음악·보컬·편곡", tokenTip: "장르·템포·구조를 먼저 고정하고 필요한 길이만 생성하세요.", promptStarter: "ElevenLabs Music에서 [분위기]의 [장르] 곡을 만들어줘. 템포는 [BPM], 구조는 [구조]야.", pricing: "공식 사이트 확인", source: "AimAtters AI Tool DB", verifiedAt: "2026-08-26", url: "https://elevenlabs.io/music", tags: ["음악", "보컬", "생성"] },
  { name: "Dreamina", slug: "dreamina", category: "영상", description: "텍스트·이미지·영상을 시네마틱 콘텐츠로 변환하는 멀티모달 AI 플랫폼입니다.", useCase: "이미지·영상 생성", tokenTip: "참조 이미지·화면비·장면 수를 먼저 고정해 재생성을 줄이세요.", promptStarter: "Dreamina에서 [참조 이미지]를 기반으로 [분위기]의 5초 시네마틱 장면을 만들어줘.", pricing: "공식 사이트 확인", source: "AimAtters AI Tool DB", verifiedAt: "2026-08-26", url: "https://dreamina.capcut.com/", tags: ["영상", "이미지", "멀티모달"] },
  { name: "QuillBot", slug: "quillbot", category: "글쓰기·문서", description: "문장 바꾸기·요약·문법 교정을 지원하는 AI 글쓰기 보조 플랫폼입니다.", useCase: "문서 교정·패러프레이즈", tokenTip: "원문 톤과 길이를 지정하고 문단 전체보다 필요한 문장만 처리하세요.", promptStarter: "QuillBot에서 이 문장을 [공식적·간결한] 톤으로 바꿔줘. 의미와 핵심 용어는 유지해줘: [문장].", pricing: "공식 사이트 확인", source: "AimAtters AI Tool DB", verifiedAt: "2026-08-26", url: "https://quillbot.com/", tags: ["글쓰기", "요약", "교정"] },
  { name: "Wan AI", slug: "wan-ai", category: "영상", description: "텍스트·이미지·영상을 시네마틱 영상으로 변환하는 Alibaba 계열 AI 플랫폼입니다.", useCase: "영상 생성·변환", tokenTip: "짧은 클립과 단일 동작으로 먼저 테스트해 생성 비용을 제한하세요.", promptStarter: "Wan AI에서 [이미지] 속 인물이 [동작]하는 5초 시네마틱 영상을 만들어줘.", pricing: "공식 사이트 확인", source: "AimAtters AI Tool DB", verifiedAt: "2026-08-26", url: "https://wan.video/", tags: ["영상", "생성", "멀티모달"] },
  { name: "Syllaby", slug: "syllaby", category: "마케팅·SNS", description: "영상 콘텐츠와 소셜미디어 게시를 자동화하는 AI 마케팅 플랫폼입니다.", useCase: "콘텐츠 기획·SNS 자동화", tokenTip: "콘텐츠 기둥과 게시 채널을 고정해 반복 아이디어 생성을 줄이세요.", promptStarter: "Syllaby에서 [타깃]을 위한 2주 영상 콘텐츠 캘린더를 훅·본문·CTA로 만들어줘.", pricing: "공식 사이트 확인", source: "AimAtters AI Tool DB", verifiedAt: "2026-08-26", url: "https://syllaby.io/", tags: ["마케팅", "SNS", "영상"] },
  { name: "Pomelli", slug: "pomelli", category: "마케팅·SNS", description: "브랜드 맥락을 바탕으로 마케팅 콘텐츠를 만드는 Google Labs 실험 도구입니다.", useCase: "브랜드 콘텐츠·캠페인", tokenTip: "브랜드 설명과 타깃을 한 번 정리해 여러 콘텐츠에 재사용하세요.", promptStarter: "Pomelli에서 [브랜드]의 [캠페인 목적]에 맞는 SNS 콘텐츠 방향 3가지를 제안해줘.", pricing: "공식 사이트 확인", source: "AimAtters AI Tool DB", verifiedAt: "2026-08-26", url: "https://labs.google.com/pomelli/", tags: ["브랜드", "마케팅", "콘텐츠"] },
  { name: "FineVoice AI", slug: "finevoice-ai", category: "음성·음악", description: "텍스트 음성 변환과 음성 생성 기능을 제공하는 AI 보이스 플랫폼입니다.", useCase: "내레이션·음성 생성", tokenTip: "스크립트를 문장 단위로 나누고 필요한 화자와 언어만 선택하세요.", promptStarter: "FineVoice AI에서 이 스크립트를 [차분한] [언어] 내레이션으로 읽어줘. 속도는 [속도]야.", pricing: "공식 사이트 확인", source: "AimAtters AI Tool DB", verifiedAt: "2026-08-26", url: "https://finevoice.ai/", tags: ["음성", "내레이션", "생성"] },
  { name: "Storytell AI", slug: "storytell-ai", category: "데이터·문서", description: "스프레드시트 자료를 바탕으로 보고서와 설명을 만드는 AI 도구입니다.", useCase: "엑셀·보고서 작성", tokenTip: "분석할 시트와 원하는 지표를 먼저 지정해 불필요한 데이터 처리를 줄이세요.", promptStarter: "Storytell AI에서 이 엑셀의 핵심 변화와 이상치를 임원용 5문장 보고서로 작성해줘: [파일].", pricing: "공식 사이트 확인", source: "AimAtters AI Tool DB", verifiedAt: "2026-08-26", url: "https://storytell.ai/", tags: ["엑셀", "데이터", "보고서"] },
  { name: "Explainpaper", slug: "explainpaper", category: "리서치·문서", description: "영어 논문의 어려운 문장을 쉽게 설명하고 읽기를 돕는 AI 도구입니다.", useCase: "논문 읽기·개념 설명", tokenTip: "논문 전체보다 막히는 문단과 용어를 선택해 질문하세요.", promptStarter: "Explainpaper에서 이 문단을 비전공자에게 설명해줘. 핵심 주장과 근거를 구분해줘: [문단].", pricing: "공식 사이트 확인", source: "AimAtters AI Tool DB", verifiedAt: "2026-08-26", url: "https://www.explainpaper.com/", tags: ["논문", "리서치", "설명"] },
  { name: "UPDF AI", slug: "updf-ai", category: "리서치·문서", description: "PDF 문서를 요약하고 편집하는 AI 문서 도구입니다.", useCase: "PDF 요약·문서 편집", tokenTip: "질문할 페이지 범위와 원하는 출력 형식을 먼저 지정하세요.", promptStarter: "UPDF AI에서 이 PDF의 결론·핵심 수치·주의사항을 페이지 번호와 함께 요약해줘: [PDF].", pricing: "공식 사이트 확인", source: "AimAtters AI Tool DB", verifiedAt: "2026-08-26", url: "https://updf.com/updf-ai/", tags: ["PDF", "문서", "요약"] },
  { name: "Topaz Photo AI", slug: "topaz-photo-ai", category: "이미지·디자인", description: "사진의 노이즈 제거와 선명도·해상도 향상을 지원하는 이미지 도구입니다.", useCase: "사진 복원·업스케일", tokenTip: "원본 해상도와 출력 크기를 먼저 정하고 필요한 보정만 적용하세요.", promptStarter: "Topaz Photo AI에서 이 사진의 노이즈를 줄이고 얼굴 디테일은 자연스럽게 보존해줘: [사진].", pricing: "공식 사이트 확인", source: "AimAtters AI Tool DB", verifiedAt: "2026-08-26", url: "https://www.topazlabs.com/topaz-photo-ai", tags: ["사진", "업스케일", "복원"] },
  { name: "Guidde", slug: "guidde", category: "업무·자동화", description: "화면 작업을 캡처해 튜토리얼과 업무 가이드로 만드는 AI 플랫폼입니다.", useCase: "튜토리얼·온보딩 문서", tokenTip: "대상 사용자와 하나의 작업 흐름을 먼저 정해 불필요한 캡처를 줄이세요.", promptStarter: "Guidde에서 [업무]를 처음 하는 사람을 위한 6단계 튜토리얼을 만들어줘. 각 단계의 주의점도 적어줘.", pricing: "공식 사이트 확인", source: "AimAtters AI Tool DB", verifiedAt: "2026-08-26", url: "https://www.guidde.com/", tags: ["튜토리얼", "업무", "문서"] },
];
