export type AimAttersTool = {
  name: string;
  slug: string;
  category: string;
  description: string;
  useCase: string;
  tokenTip: string;
  promptStarter: string;
  pricing: string;
  source: string;
  verifiedAt: string;
  url: string;
  tags: string[];
};

/** Curated from the visible AimAtters AI Tool DB entries; official product URLs are used for actions. */
export const aimattersTools: AimAttersTool[] = [
  { name: "10Web AI", slug: "10web-ai", category: "바이브코딩", description: "AI로 WordPress 웹사이트를 생성하고 관리하는 웹사이트 제작 도구입니다.", useCase: "웹사이트 제작·랜딩페이지", tokenTip: "사이트 목적·페이지 수·필수 섹션을 먼저 고정하고 한 번에 한 화면씩 수정하세요.", promptStarter: "10Web AI로 [사이트 목적]의 첫 화면을 만들어줘. 필수 섹션은 [목록], 톤은 [톤], 모바일 우선으로 구성해줘.", pricing: "공식 사이트 확인", source: "AimAtters AI Tool DB", verifiedAt: "2026-08-26", url: "https://10web.io/", tags: ["웹사이트", "WordPress", "바이브코딩"] },
  { name: "Colossyan", slug: "colossyan", category: "영상", description: "AI 아바타와 텍스트 기반 편집으로 교육·온보딩 영상을 제작하는 플랫폼입니다.", useCase: "교육 영상·온보딩", tokenTip: "장면마다 한 메시지만 배치하고 긴 원고는 챕터로 나눠 재생성 비용을 줄이세요.", promptStarter: "Colossyan용 교육 영상 원고를 6개 장면으로 나눠줘. 대상은 [대상], 목표는 [목표], 장면당 35단어 이내로 작성해줘.", pricing: "공식 사이트 확인", source: "AimAtters AI Tool DB", verifiedAt: "2026-08-26", url: "https://www.colossyan.com/", tags: ["아바타", "교육", "영상"] },
  { name: "Elai.io", slug: "elai-io", category: "영상", description: "텍스트를 AI 아바타 교육 영상으로 바꾸는 비디오 제작 플랫폼입니다.", useCase: "교육 콘텐츠·설명 영상", tokenTip: "공통 인트로와 아웃트로를 템플릿화하고 본문 장면만 교체하세요.", promptStarter: "Elai.io에서 [주제]를 설명하는 5분 교육 영상 구조를 장면·내레이션·화면 자막으로 나눠줘.", pricing: "공식 사이트 확인", source: "AimAtters AI Tool DB", verifiedAt: "2026-08-26", url: "https://elai.io/", tags: ["아바타", "교육", "영상"] },
  { name: "FlexClip AI", slug: "flexclip-ai", category: "영상", description: "긴 영상을 숏폼 콘텐츠로 편집하고 자막·장면 구성을 돕는 AI 영상 도구입니다.", useCase: "숏폼·영상 편집", tokenTip: "원본 영상의 핵심 타임코드와 목표 채널을 먼저 지정해 후보 장면을 줄이세요.", promptStarter: "FlexClip AI에서 [원본 주제] 영상의 30초 숏폼 3개를 제안해줘. 각 영상은 훅·핵심·CTA로 구성해줘.", pricing: "공식 사이트 확인", source: "AimAtters AI Tool DB", verifiedAt: "2026-08-26", url: "https://www.flexclip.com/", tags: ["영상 편집", "숏폼", "콘텐츠"] },
  { name: "Knowt", slug: "knowt", category: "문서·리서치", description: "노트와 학습 자료를 플래시카드와 퀴즈로 바꾸는 AI 학습 도구입니다.", useCase: "학습자료·퀴즈", tokenTip: "시험 범위와 난이도를 먼저 지정하고 자료 전체보다 필요한 챕터만 입력하세요.", promptStarter: "Knowt에서 다음 학습자료를 초급·중급·고급 플래시카드로 나누고 각 카드에 정답 근거를 붙여줘: [자료].", pricing: "공식 사이트 확인", source: "AimAtters AI Tool DB", verifiedAt: "2026-08-26", url: "https://knowt.com/", tags: ["학습", "퀴즈", "문서"] },
  { name: "Quizgecko", slug: "quizgecko", category: "문서·리서치", description: "학습 자료에서 퀴즈와 시험 문제를 자동으로 생성하는 AI 도구입니다.", useCase: "퀴즈·평가 문항", tokenTip: "문항 수·문제 유형·정답 근거를 고정해 불필요한 재생성을 줄이세요.", promptStarter: "Quizgecko용 평가 문항을 만들어줘. 대상은 [대상], 문항 수는 10개, 유형은 객관식 6개와 서술형 4개로 해줘.", pricing: "공식 사이트 확인", source: "AimAtters AI Tool DB", verifiedAt: "2026-08-26", url: "https://quizgecko.com/", tags: ["학습", "퀴즈", "교육"] },
  { name: "Mindgrasp", slug: "mindgrasp", category: "문서·리서치", description: "강의와 문서를 요약하고 질문에 답하는 AI 학습 보조 도구입니다.", useCase: "강의·문서 요약", tokenTip: "요약 목적과 원하는 길이를 먼저 지정하고 후속 질문은 한 주제씩 묻세요.", promptStarter: "Mindgrasp에서 [자료]를 시험 대비용으로 요약해줘. 핵심 개념·예시·헷갈리는 점·복습 질문 순서로 정리해줘.", pricing: "공식 사이트 확인", source: "AimAtters AI Tool DB", verifiedAt: "2026-08-26", url: "https://mindgrasp.ai/", tags: ["학습", "문서", "요약"] },
  { name: "StudyFetch", slug: "studyfetch", category: "문서·리서치", description: "수업 자료를 AI 노트·퀴즈·플래시카드로 변환하는 학습 플랫폼입니다.", useCase: "수업자료·시험준비", tokenTip: "자료를 과목·주차별로 나눠 업로드하고 원하는 산출물만 먼저 생성하세요.", promptStarter: "StudyFetch에서 [과목] 자료를 주차별 복습 노트와 플래시카드로 정리해줘. 시험에 나올 가능성이 높은 개념을 표시해줘.", pricing: "공식 사이트 확인", source: "AimAtters AI Tool DB", verifiedAt: "2026-08-26", url: "https://www.studyfetch.com/", tags: ["학습", "플래시카드", "문서"] },
  { name: "Reclaim.ai", slug: "reclaim-ai", category: "업무·자동화", description: "할 일과 반복 일정을 캘린더 빈 시간에 자동으로 배치하는 일정 관리 도구입니다.", useCase: "일정·집중시간·업무계획", tokenTip: "업무 우선순위·소요시간·마감만 정확히 입력하고 세부 설명은 캘린더 메모로 분리하세요.", promptStarter: "Reclaim.ai에서 [업무 목록]을 이번 주 일정에 배치해줘. 우선순위는 [기준], 집중 시간은 하루 [시간]으로 보호해줘.", pricing: "공식 사이트 확인", source: "AimAtters AI Tool DB", verifiedAt: "2026-08-26", url: "https://reclaim.ai/", tags: ["일정", "생산성", "자동화"] },
  { name: "Sembly AI", slug: "sembly-ai", category: "회의·전사", description: "회의 내용을 기록하고 실행 가능한 업무와 요약으로 정리하는 AI 회의 비서입니다.", useCase: "회의록·액션아이템", tokenTip: "회의 목적과 참석자 역할을 미리 설정해 요약에서 필요한 결정과 담당자를 우선 추출하세요.", promptStarter: "Sembly AI 회의록에서 결정사항·담당자·마감일·미해결 질문만 표로 정리해줘.", pricing: "공식 사이트 확인", source: "AimAtters AI Tool DB", verifiedAt: "2026-08-26", url: "https://www.sembly.ai/", tags: ["회의", "전사", "업무"] },
  { name: "Notta", slug: "notta", category: "회의·전사", description: "회의·인터뷰·강의를 전사하고 번역·요약하는 AI 전사 도구입니다.", useCase: "전사·번역·회의 요약", tokenTip: "언어와 화자 수를 먼저 지정하고 전체 재요약보다 필요한 구간만 후속 처리하세요.", promptStarter: "Notta 전사본에서 발언자별 핵심 주장과 후속 할 일을 한국어로 요약해줘. 불명확한 부분은 [확인 필요]로 표시해줘.", pricing: "공식 사이트 확인", source: "AimAtters AI Tool DB", verifiedAt: "2026-08-26", url: "https://www.notta.ai/", tags: ["회의", "전사", "번역"] },
  { name: "Avoma", slug: "avoma", category: "회의·전사", description: "회의 요약과 세일즈 코칭을 지원하는 AI 미팅 인텔리전스 플랫폼입니다.", useCase: "세일즈 회의·코칭", tokenTip: "회의 유형별 템플릿을 고정해 매번 전체 녹취를 같은 방식으로 분석하지 않도록 하세요.", promptStarter: "Avoma에서 이 세일즈 미팅을 니즈·반대 의견·다음 단계·리스크 기준으로 코칭해줘: [전사].", pricing: "공식 사이트 확인", source: "AimAtters AI Tool DB", verifiedAt: "2026-08-26", url: "https://www.avoma.com/", tags: ["회의", "세일즈", "코칭"] },
  { name: "TurboScribe", slug: "turboscribe", category: "회의·전사", description: "대용량 음성·영상 파일을 텍스트로 변환하는 AI 전사 서비스입니다.", useCase: "대용량 전사·자막", tokenTip: "긴 파일은 필요한 구간을 먼저 분리하고 언어·출력 형식을 미리 지정하세요.", promptStarter: "TurboScribe 전사본에서 60초 단위 핵심 구간과 자막용 문장을 추출해줘.", pricing: "공식 사이트 확인", source: "AimAtters AI Tool DB", verifiedAt: "2026-08-26", url: "https://turboscribe.ai/", tags: ["전사", "자막", "음성"] },
  { name: "tl;dv", slug: "tl-dv", category: "회의·전사", description: "화상회의를 녹화·전사하고 핵심 내용을 요약하는 회의 비서입니다.", useCase: "화상회의·회의 검색", tokenTip: "회의 아젠다와 원하는 요약 항목을 미리 설정해 전체 녹취 재처리를 줄이세요.", promptStarter: "tl;dv에서 회의별 결정사항과 담당자 액션을 팀 공유용 5줄 요약으로 만들어줘.", pricing: "공식 사이트 확인", source: "AimAtters AI Tool DB", verifiedAt: "2026-08-26", url: "https://www.tldv.io/", tags: ["회의", "전사", "요약"] },
  { name: "Moises", slug: "moises", category: "음성·음악", description: "보컬·악기 분리와 음악 연습을 지원하는 AI 음악 도구입니다.", useCase: "음악 연습·트랙 분리", tokenTip: "필요한 스템만 선택하고 전체 믹스를 반복 업로드하지 않도록 원본을 보관하세요.", promptStarter: "Moises에서 [곡]을 보컬·드럼·베이스·기타로 분리하고 [악기] 연습용 루프를 구성해줘.", pricing: "공식 사이트 확인", source: "AimAtters AI Tool DB", verifiedAt: "2026-08-26", url: "https://moises.ai/", tags: ["음악", "오디오", "연습"] },
  { name: "Sonix", slug: "sonix", category: "회의·전사", description: "음성·영상 파일을 텍스트로 전사하고 번역하는 AI 서비스입니다.", useCase: "전사·번역·자막", tokenTip: "목표 언어와 자막 형식을 먼저 정하고 필요한 구간만 교정하세요.", promptStarter: "Sonix 전사본을 [언어] 자막용으로 다듬어줘. 화자 구분과 타임코드는 유지해줘.", pricing: "공식 사이트 확인", source: "AimAtters AI Tool DB", verifiedAt: "2026-08-26", url: "https://sonix.ai/", tags: ["전사", "번역", "자막"] },
  { name: "Kits AI", slug: "kits-ai", category: "음성·음악", description: "보컬 변환과 음성 클로닝을 지원하는 음악 제작용 AI 보이스 도구입니다.", useCase: "보컬·음성 제작", tokenTip: "짧은 프레이즈로 먼저 테스트하고 권리·동의가 확인된 음성만 사용하세요.", promptStarter: "Kits AI에서 [곡 분위기]에 맞는 보컬 프레이즈를 설계해줘. 음역·템포·발음 주의점을 함께 적어줘.", pricing: "공식 사이트 확인", source: "AimAtters AI Tool DB", verifiedAt: "2026-08-26", url: "https://www.kits.ai/", tags: ["음성", "음악", "보컬"] },
  { name: "Cleanvoice AI", slug: "cleanvoice-ai", category: "음성·음악", description: "팟캐스트의 노이즈와 말버릇을 자동으로 정리하는 AI 오디오 편집 도구입니다.", useCase: "팟캐스트·오디오 편집", tokenTip: "원본 파일을 보관하고 제거 강도를 낮게 시작해 자연스러운 결과를 우선 확인하세요.", promptStarter: "Cleanvoice AI에서 팟캐스트의 반복어·긴 침묵·배경 노이즈를 자연스럽게 정리해줘. 말투와 의미는 보존해줘.", pricing: "공식 사이트 확인", source: "AimAtters AI Tool DB", verifiedAt: "2026-08-26", url: "https://cleanvoice.ai/", tags: ["오디오", "팟캐스트", "편집"] },
];
