import type { DirectoryTool } from "./toolCatalog";

/** Google 공식 제품·실험 페이지에서 확인한 우선 편입 도구입니다. */
export const googleLabsTools: DirectoryTool[] = [
  {
    id: 0,
    slug: "notebooklm-gemini-notebook",
    name: "NotebookLM",
    category: "학습·리서치",
    sourceCategory: "Google 공식",
    description: "내가 제공한 자료를 바탕으로 요약·질문·오디오 개요를 만드는 연구·학습 도구입니다. 현재 Gemini Notebook으로 확장 안내되고 있습니다.",
    useCase: "논문·PDF 학습, 자료 기반 리서치, 오디오 개요",
    tokenTip: "자료 범위와 질문의 출력 필드를 먼저 제한하고, 한 번에 한 주제만 후속 질문하세요.",
    promptStarter: "NotebookLM에서 업로드한 자료만 근거로 [주제]를 초보자용으로 설명해줘. 핵심 개념·근거 위치·복습 질문 3개를 분리하고 자료 밖의 내용은 추측하지 마.",
    pricing: "무료 시작 · Plus/Pro/Ultra 플랜",
    source: "Google Gemini Notebook 공식",
    verifiedAt: "2026-08-27",
    url: "https://notebooklm.google.com/",
    pricingUrl: "https://notebook.google/plans",
    tags: ["학습", "리서치", "문서", "오디오"]
  },
  {
    id: 0,
    slug: "google-stitch",
    name: "Google Stitch",
    category: "UI·UX 디자인",
    sourceCategory: "Google Labs 공식",
    description: "자연어와 이미지 아이디어를 모바일·웹 애플리케이션 UI 디자인으로 바꾸는 AI 디자인 도구입니다.",
    useCase: "앱 화면 시안, 웹 UI 콘셉트, 멀티스크린 플로우",
    tokenTip: "대상 사용자·화면 목적·필수 컴포넌트·브랜드 톤을 먼저 고정하고 화면 단위로 생성하세요.",
    promptStarter: "Google Stitch에서 [대상 사용자]를 위한 [앱/웹 화면]을 설계해줘. 핵심 작업은 [작업], 화면은 [수]개, 모바일 우선, 접근 가능한 대비와 명확한 상태를 포함해줘.",
    pricing: "공식 페이지에서 이용 조건 확인",
    source: "Google Stitch 공식",
    verifiedAt: "2026-08-27",
    url: "https://stitch.withgoogle.com/",
    tags: ["UI", "UX", "프로토타입", "웹", "모바일"]
  },
  {
    id: 0,
    slug: "google-flow-video",
    name: "Flow AI (Google Flow)",
    category: "영상",
    sourceCategory: "Google Labs 공식",
    description: "실제 또는 생성된 참조 이미지·영상으로 장면과 이야기를 만들고 편집하는 Google AI 영상 제작 도구입니다.",
    useCase: "생성형 영상, 시네마틱 장면, 참조 기반 영상 편집",
    tokenTip: "장면·피사체·카메라·움직임·오디오 요구사항을 분리하고 짧은 샷부터 검증하세요.",
    promptStarter: "Google Flow에서 [주제]의 [초 수]초 영상을 만들어줘. 피사체는 [피사체], 장소는 [장소], 카메라는 [움직임], 분위기는 [톤], 원하지 않는 요소는 [목록]이야.",
    pricing: "공식 페이지에서 이용 조건 확인",
    source: "Google Flow 공식",
    verifiedAt: "2026-08-27",
    url: "https://labs.google/fx/tools/flow",
    tags: ["영상", "Veo", "생성", "편집"]
  },
  {
    id: 0,
    slug: "google-ai-studio",
    name: "Google AI Studio",
    category: "AI 개발",
    sourceCategory: "Google 공식",
    description: "Gemini·Veo·Lyria 등 최신 모델을 프롬프트로 실험하고 Gemini API 기반 앱을 프로토타이핑하는 개발 환경입니다.",
    useCase: "프롬프트 실험, Gemini API 앱, 멀티모달 프로토타입",
    tokenTip: "모델·입력 자료·원하는 JSON 필드·출력 길이를 먼저 지정하고 긴 배경 설명은 첨부 자료로 분리하세요.",
    promptStarter: "Google AI Studio에서 [앱 목적]을 만드는 프로토타입을 설계해줘. 입력은 [입력], 출력 JSON 필드는 [필드], 오류 시에는 [fallback]을 사용하고 API 연결 지점을 표시해줘.",
    pricing: "무료 시작 · API 사용량별 과금 가능",
    source: "Google AI Studio 공식",
    verifiedAt: "2026-08-27",
    url: "https://aistudio.google.com/welcome",
    pricingUrl: "https://aistudio.google.com/docs/pricing",
    tags: ["Gemini", "API", "개발", "프로토타입"]
  },
  {
    id: 0,
    slug: "pomelli",
    name: "Pomelli",
    category: "브랜드·마케팅",
    sourceCategory: "Google Labs 공식",
    description: "비즈니스의 브랜드 맥락을 바탕으로 일관된 마케팅 콘텐츠를 만드는 Google Labs 실험 도구입니다.",
    useCase: "브랜드 콘텐츠, 캠페인 아이디어, SNS 마케팅",
    tokenTip: "브랜드 설명·타깃·금지 표현을 한 번 정리한 뒤 채널별 변환만 요청하세요.",
    promptStarter: "Pomelli에서 [브랜드]의 [캠페인 목적]에 맞는 콘텐츠 방향 3가지를 제안해줘. 타깃은 [타깃], 채널은 [채널], 브랜드 톤은 [톤]이고 근거 없는 주장과 과장된 성과 수치는 제외해줘.",
    pricing: "Google Labs 실험 · 공식 이용 조건 확인",
    source: "Google Pomelli 공식",
    verifiedAt: "2026-08-27",
    url: "https://labs.google.com/pomelli/about/",
    tags: ["브랜드", "마케팅", "SNS", "콘텐츠"]
  },
  {
    id: 0,
    slug: "google-antigravity",
    name: "Google Antigravity",
    category: "AI 개발",
    sourceCategory: "Google 공식",
    description: "여러 로컬 에이전트를 관리하고 agent-first 방식으로 소프트웨어를 만드는 Google의 에이전트형 개발 플랫폼입니다.",
    useCase: "에이전트 개발, 코드 프로토타이핑, 로컬 개발 작업 관리",
    tokenTip: "에이전트별 목표·파일 범위·완료 조건·사람의 승인 지점을 먼저 나누고 작은 작업으로 실행하세요.",
    promptStarter: "Google Antigravity에서 [기능]을 구현해줘. 수정 가능한 파일은 [범위], 완료 조건은 [조건], 실행할 테스트는 [테스트], 위험하거나 되돌리기 어려운 작업은 먼저 승인을 요청해줘.",
    pricing: "공식 Pricing 페이지 확인",
    source: "Google Antigravity 공식",
    verifiedAt: "2026-08-27",
    url: "https://antigravity.google/",
    pricingUrl: "https://antigravity.google/pricing",
    tags: ["개발", "에이전트", "코딩", "프로토타입"]
  },
  {
    id: 0,
    slug: "google-illuminate",
    name: "Illuminate",
    category: "학습·리서치",
    sourceCategory: "Google 실험 공식",
    description: "웹 콘텐츠를 학습 선호도에 맞춰 AI 생성 오디오 토론으로 바꾸는 Google의 학습 실험 도구입니다.",
    useCase: "연구 논문 이해, 오디오 학습, 컴퓨터 과학 자료 복습",
    tokenTip: "읽을 자료의 범위와 학습 목표를 먼저 정하고, 생성된 오디오는 원문과 대조해 확인하세요.",
    promptStarter: "Illuminate에서 [논문·자료]의 핵심을 학습용 오디오 토론으로 정리해줘. 대상 수준은 [수준], 반드시 포함할 개념은 [목록], 원문에 없는 내용은 별도로 표시해줘.",
    pricing: "실험·waitlist 안내",
    source: "Google Illuminate 공식",
    verifiedAt: "2026-08-27",
    url: "https://illuminate.google.com/explore",
    tags: ["학습", "논문", "오디오", "리서치"]
  },
  {
    id: 0,
    slug: "google-textfx",
    name: "TextFX",
    category: "글쓰기·창작",
    sourceCategory: "Google 공식 실험",
    description: "언어와 작사 기법에서 영감을 받아 글쓰기 가능성을 넓히고 텍스트를 새로운 방식으로 탐색하게 하는 창작 도구 모음입니다.",
    useCase: "아이디어 발산, 표현 실험, 창의적 글쓰기",
    tokenTip: "완성 원고를 한 번에 요청하지 말고 핵심 단어·비유·관점·문장 변형처럼 한 단계씩 실험하세요.",
    promptStarter: "TextFX 방식으로 [주제]를 탐색해줘. 먼저 핵심 단어 10개, 감각적 비유 5개, 서로 다른 관점 3개를 제안하고 최종 문장은 내가 선택한 뒤 작성할게.",
    pricing: "공식 실험 페이지에서 이용 조건 확인",
    source: "Google TextFX 공식",
    verifiedAt: "2026-08-27",
    url: "https://textfx.withgoogle.com/",
    tags: ["글쓰기", "창작", "언어", "아이디어"]
  },
  {
    id: 0,
    slug: "google-opal",
    name: "Google Opal",
    category: "노코드·앱 제작",
    sourceCategory: "Google Labs 공식",
    description: "자연어로 AI 미니앱을 만들고 편집하고 공유하는 Google Labs 실험 도구입니다.",
    useCase: "노코드 미니앱, 업무 자동화 프로토타입, 아이디어 검증",
    tokenTip: "입력·변환·출력 단계를 먼저 3개 안팎으로 단순화하고, 한 번에 한 단계만 수정하세요.",
    promptStarter: "Google Opal에서 [사용자]가 [문제]를 해결하는 미니앱을 만들어줘. 입력은 [입력], 처리 단계는 [단계], 출력은 [형식], 실패 시 안내와 개인정보 주의 문구를 포함해줘.",
    pricing: "Google Labs 실험 · 공식 이용 조건 확인",
    source: "Google Opal 공식",
    verifiedAt: "2026-08-27",
    url: "https://opal.google/",
    tags: ["노코드", "앱", "자동화", "프로토타입"]
  },
  {
    id: 0,
    slug: "musicfx-google-flow-music",
    name: "MusicFX (Google Flow Music)",
    category: "AI 음악",
    sourceCategory: "Google 공식",
    description: "자연어 대화로 곡을 만들고 편집·리믹스·게시·공유하는 Google의 음악 생성 서비스입니다.",
    useCase: "AI 음악, 가사 브레인스토밍, 음악 리믹스, AI 뮤직비디오",
    tokenTip: "장르·템포·악기·곡 길이·보컬 여부를 먼저 고정하고 짧은 후보를 비교한 뒤 전체 곡을 만드세요.",
    promptStarter: "MusicFX에서 [장르]의 [분위기] 곡을 만들어줘. 템포는 [BPM], 주요 악기는 [악기], 구조는 [구조], 보컬은 [있음/없음], 사용 권리와 공개 범위가 불명확한 요소는 표시해줘.",
    pricing: "무료 시작 · 일일 크레딧 안내",
    source: "Google Flow Music 공식",
    verifiedAt: "2026-08-27",
    url: "https://www.flowmusic.app/",
    tags: ["음악", "작곡", "리믹스", "뮤직비디오"]
  }
];
