export type KSkillCategory = "교통" | "공공서비스" | "생활" | "쇼핑" | "금융·비즈니스" | "문서·개발" | "콘텐츠·검색" | "기타";

export type KSkillEntry = { slug: string; name: string; category: KSkillCategory; url: string };

export const kSkillCatalog: KSkillEntry[] = [
  { slug: "assembly-bill-vote-search", name: "Assembly Bill Vote Search", category: "콘텐츠·검색", url: "https://github.com/NomaDamas/k-skill/tree/main/assembly-bill-vote-search" },
  { slug: "biz-health-check", name: "Biz Health Check", category: "금융·비즈니스", url: "https://github.com/NomaDamas/k-skill/tree/main/biz-health-check" },
  { slug: "bok-ecos-stats", name: "Bok Ecos Stats", category: "금융·비즈니스", url: "https://github.com/NomaDamas/k-skill/tree/main/bok-ecos-stats" },
  { slug: "building-register-search", name: "Building Register Search", category: "공공서비스", url: "https://github.com/NomaDamas/k-skill/tree/main/building-register-search" },
  { slug: "bunjang-search", name: "Bunjang Search", category: "쇼핑", url: "https://github.com/NomaDamas/k-skill/tree/main/bunjang-search" },
  { slug: "cheap-gas-nearby", name: "Cheap Gas Nearby", category: "생활", url: "https://github.com/NomaDamas/k-skill/tree/main/cheap-gas-nearby" },
  { slug: "corporate-registration-consulting", name: "Corporate Registration Consulting", category: "공공서비스", url: "https://github.com/NomaDamas/k-skill/tree/main/corporate-registration-consulting" },
  { slug: "coupang-product-search", name: "Coupang Product Search", category: "쇼핑", url: "https://github.com/NomaDamas/k-skill/tree/main/coupang-product-search" },
  { slug: "court-auction-notice-search", name: "Court Auction Notice Search", category: "공공서비스", url: "https://github.com/NomaDamas/k-skill/tree/main/court-auction-notice-search" },
  { slug: "court-payment-order-assistant", name: "Court Payment Order Assistant", category: "공공서비스", url: "https://github.com/NomaDamas/k-skill/tree/main/court-payment-order-assistant" },
  { slug: "d2b-notice-search", name: "D2b Notice Search", category: "콘텐츠·검색", url: "https://github.com/NomaDamas/k-skill/tree/main/d2b-notice-search" },
  { slug: "daangn-cars-search", name: "Daangn Cars Search", category: "생활", url: "https://github.com/NomaDamas/k-skill/tree/main/daangn-cars-search" },
  { slug: "daangn-jobs-search", name: "Daangn Jobs Search", category: "생활", url: "https://github.com/NomaDamas/k-skill/tree/main/daangn-jobs-search" },
  { slug: "daangn-realty-search", name: "Daangn Realty Search", category: "생활", url: "https://github.com/NomaDamas/k-skill/tree/main/daangn-realty-search" },
  { slug: "daangn-used-goods-search", name: "Daangn Used Goods Search", category: "쇼핑", url: "https://github.com/NomaDamas/k-skill/tree/main/daangn-used-goods-search" },
  { slug: "daishin-report-search", name: "Daishin Report Search", category: "금융·비즈니스", url: "https://github.com/NomaDamas/k-skill/tree/main/daishin-report-search" },
  { slug: "daiso-product-search", name: "Daiso Product Search", category: "쇼핑", url: "https://github.com/NomaDamas/k-skill/tree/main/daiso-product-search" },
  { slug: "danawa-price-search", name: "Danawa Price Search", category: "쇼핑", url: "https://github.com/NomaDamas/k-skill/tree/main/danawa-price-search" },
  { slug: "delivery-tracking", name: "Delivery Tracking", category: "교통", url: "https://github.com/NomaDamas/k-skill/tree/main/delivery-tracking" },
  { slug: "donation-place-search", name: "Donation Place Search", category: "공공서비스", url: "https://github.com/NomaDamas/k-skill/tree/main/donation-place-search" },
  { slug: "emergency-room-beds", name: "Emergency Room Beds", category: "생활", url: "https://github.com/NomaDamas/k-skill/tree/main/emergency-room-beds" },
  { slug: "ev-charger-nearby", name: "Ev Charger Nearby", category: "생활", url: "https://github.com/NomaDamas/k-skill/tree/main/ev-charger-nearby" },
  { slug: "ev-subsidy-status", name: "Ev Subsidy Status", category: "생활", url: "https://github.com/NomaDamas/k-skill/tree/main/ev-subsidy-status" },
  { slug: "express-bus-booking", name: "Express Bus Booking", category: "교통", url: "https://github.com/NomaDamas/k-skill/tree/main/express-bus-booking" },
  { slug: "fine-dust-location", name: "Fine Dust Location", category: "생활", url: "https://github.com/NomaDamas/k-skill/tree/main/fine-dust-location" },
  { slug: "flight-ticket-search", name: "Flight Ticket Search", category: "교통", url: "https://github.com/NomaDamas/k-skill/tree/main/flight-ticket-search" },
  { slug: "foresttrip-vacancy", name: "Foresttrip Vacancy", category: "기타", url: "https://github.com/NomaDamas/k-skill/tree/main/foresttrip-vacancy" },
  { slug: "fsc-corporate-info", name: "Fsc Corporate Info", category: "금융·비즈니스", url: "https://github.com/NomaDamas/k-skill/tree/main/fsc-corporate-info" },
  { slug: "g2b-order-plan-search", name: "G2b Order Plan Search", category: "공공서비스", url: "https://github.com/NomaDamas/k-skill/tree/main/g2b-order-plan-search" },
  { slug: "g2b-sanctioned-supplier", name: "G2b Sanctioned Supplier", category: "공공서비스", url: "https://github.com/NomaDamas/k-skill/tree/main/g2b-sanctioned-supplier" },
  { slug: "geeknews-search", name: "Geeknews Search", category: "콘텐츠·검색", url: "https://github.com/NomaDamas/k-skill/tree/main/geeknews-search" },
  { slug: "gongsijiga-search", name: "Gongsijiga Search", category: "콘텐츠·검색", url: "https://github.com/NomaDamas/k-skill/tree/main/gongsijiga-search" },
  { slug: "gov-overseas-trip-report", name: "Gov Overseas Trip Report", category: "공공서비스", url: "https://github.com/NomaDamas/k-skill/tree/main/gov-overseas-trip-report" },
  { slug: "han-river-water-level", name: "Han River Water Level", category: "생활", url: "https://github.com/NomaDamas/k-skill/tree/main/han-river-water-level" },
  { slug: "hankookilbo-news", name: "Hankookilbo News", category: "콘텐츠·검색", url: "https://github.com/NomaDamas/k-skill/tree/main/hankookilbo-news" },
  { slug: "highway-traffic-status", name: "Highway Traffic Status", category: "교통", url: "https://github.com/NomaDamas/k-skill/tree/main/highway-traffic-status" },
  { slug: "hola-poke-yeoksam", name: "Hola Poke Yeoksam", category: "생활", url: "https://github.com/NomaDamas/k-skill/tree/main/hola-poke-yeoksam" },
  { slug: "household-waste-info", name: "Household Waste Info", category: "공공서비스", url: "https://github.com/NomaDamas/k-skill/tree/main/household-waste-info" },
  { slug: "housing-official-price", name: "Housing Official Price", category: "생활", url: "https://github.com/NomaDamas/k-skill/tree/main/housing-official-price" },
  { slug: "hwp", name: "Hwp", category: "문서·개발", url: "https://github.com/NomaDamas/k-skill/tree/main/hwp" },
  { slug: "intercity-bus-booking", name: "Intercity Bus Booking", category: "교통", url: "https://github.com/NomaDamas/k-skill/tree/main/intercity-bus-booking" },
  { slug: "iros-registry-automation", name: "Iros Registry Automation", category: "공공서비스", url: "https://github.com/NomaDamas/k-skill/tree/main/iros-registry-automation" },
  { slug: "job-posting-match", name: "Job Posting Match", category: "기타", url: "https://github.com/NomaDamas/k-skill/tree/main/job-posting-match" },
  { slug: "jobkorea-talent-search", name: "Jobkorea Talent Search", category: "콘텐츠·검색", url: "https://github.com/NomaDamas/k-skill/tree/main/jobkorea-talent-search" },
  { slug: "joseon-sillok-search", name: "Joseon Sillok Search", category: "금융·비즈니스", url: "https://github.com/NomaDamas/k-skill/tree/main/joseon-sillok-search" },
  { slug: "k-dart", name: "K Dart", category: "금융·비즈니스", url: "https://github.com/NomaDamas/k-skill/tree/main/k-dart" },
  { slug: "k-schoollunch-menu", name: "K Schoollunch Menu", category: "공공서비스", url: "https://github.com/NomaDamas/k-skill/tree/main/k-schoollunch-menu" },
  { slug: "kakao-bar-nearby", name: "Kakao Bar Nearby", category: "생활", url: "https://github.com/NomaDamas/k-skill/tree/main/kakao-bar-nearby" },
  { slug: "kakao-map", name: "Kakao Map", category: "생활", url: "https://github.com/NomaDamas/k-skill/tree/main/kakao-map" },
  { slug: "kakaotalk-mac", name: "Kakaotalk Mac", category: "기타", url: "https://github.com/NomaDamas/k-skill/tree/main/kakaotalk-mac" },
  { slug: "kbl-results", name: "Kbl Results", category: "금융·비즈니스", url: "https://github.com/NomaDamas/k-skill/tree/main/kbl-results" },
  { slug: "kbo-results", name: "Kbo Results", category: "금융·비즈니스", url: "https://github.com/NomaDamas/k-skill/tree/main/kbo-results" },
  { slug: "keris-academic-search", name: "Keris Academic Search", category: "콘텐츠·검색", url: "https://github.com/NomaDamas/k-skill/tree/main/keris-academic-search" },
  { slug: "kleague-results", name: "Kleague Results", category: "금융·비즈니스", url: "https://github.com/NomaDamas/k-skill/tree/main/kleague-results" },
  { slug: "kopis-performance-search", name: "Kopis Performance Search", category: "금융·비즈니스", url: "https://github.com/NomaDamas/k-skill/tree/main/kopis-performance-search" },
  { slug: "korea-weather", name: "Korea Weather", category: "생활", url: "https://github.com/NomaDamas/k-skill/tree/main/korea-weather" },
  { slug: "korean-character-count", name: "Korean Character Count", category: "콘텐츠·검색", url: "https://github.com/NomaDamas/k-skill/tree/main/korean-character-count" },
  { slug: "korean-cinema-search", name: "Korean Cinema Search", category: "콘텐츠·검색", url: "https://github.com/NomaDamas/k-skill/tree/main/korean-cinema-search" },
  { slug: "korean-heritage-search", name: "Korean Heritage Search", category: "공공서비스", url: "https://github.com/NomaDamas/k-skill/tree/main/korean-heritage-search" },
  { slug: "korean-holiday-calendar", name: "Korean Holiday Calendar", category: "공공서비스", url: "https://github.com/NomaDamas/k-skill/tree/main/korean-holiday-calendar" },
  { slug: "korean-humanizer", name: "Korean Humanizer", category: "콘텐츠·검색", url: "https://github.com/NomaDamas/k-skill/tree/main/korean-humanizer" },
  { slug: "korean-jangbu-for", name: "Korean Jangbu For", category: "기타", url: "https://github.com/NomaDamas/k-skill/tree/main/korean-jangbu-for" },
  { slug: "korean-law-search", name: "Korean Law Search", category: "공공서비스", url: "https://github.com/NomaDamas/k-skill/tree/main/korean-law-search" },
  { slug: "korean-marathon-schedule", name: "Korean Marathon Schedule", category: "금융·비즈니스", url: "https://github.com/NomaDamas/k-skill/tree/main/korean-marathon-schedule" },
  { slug: "korean-middle-korean", name: "Korean Middle Korean", category: "콘텐츠·검색", url: "https://github.com/NomaDamas/k-skill/tree/main/korean-middle-korean" },
  { slug: "korean-patent-search", name: "Korean Patent Search", category: "공공서비스", url: "https://github.com/NomaDamas/k-skill/tree/main/korean-patent-search" },
  { slug: "korean-privacy-terms", name: "Korean Privacy Terms", category: "콘텐츠·검색", url: "https://github.com/NomaDamas/k-skill/tree/main/korean-privacy-terms" },
  { slug: "korean-scholarship-search", name: "Korean Scholarship Search", category: "공공서비스", url: "https://github.com/NomaDamas/k-skill/tree/main/korean-scholarship-search" },
  { slug: "korean-slang-writing", name: "Korean Slang Writing", category: "콘텐츠·검색", url: "https://github.com/NomaDamas/k-skill/tree/main/korean-slang-writing" },
  { slug: "korean-spell-check", name: "Korean Spell Check", category: "콘텐츠·검색", url: "https://github.com/NomaDamas/k-skill/tree/main/korean-spell-check" },
  { slug: "korean-stock-search", name: "Korean Stock Search", category: "금융·비즈니스", url: "https://github.com/NomaDamas/k-skill/tree/main/korean-stock-search" },
  { slug: "korean-transit-route", name: "Korean Transit Route", category: "교통", url: "https://github.com/NomaDamas/k-skill/tree/main/korean-transit-route" },
  { slug: "kosis-stats", name: "Kosis Stats", category: "금융·비즈니스", url: "https://github.com/NomaDamas/k-skill/tree/main/kosis-stats" },
  { slug: "kr-whois-lookup", name: "Kr Whois Lookup", category: "기타", url: "https://github.com/NomaDamas/k-skill/tree/main/kr-whois-lookup" },
  { slug: "kstartup-search", name: "Kstartup Search", category: "공공서비스", url: "https://github.com/NomaDamas/k-skill/tree/main/kstartup-search" },
  { slug: "ktx-booking", name: "Ktx Booking", category: "교통", url: "https://github.com/NomaDamas/k-skill/tree/main/ktx-booking" },
  { slug: "lck-analytics", name: "Lck Analytics", category: "금융·비즈니스", url: "https://github.com/NomaDamas/k-skill/tree/main/lck-analytics" },
  { slug: "lh-notice-search", name: "Lh Notice Search", category: "공공서비스", url: "https://github.com/NomaDamas/k-skill/tree/main/lh-notice-search" },
  { slug: "library-book-search", name: "Library Book Search", category: "공공서비스", url: "https://github.com/NomaDamas/k-skill/tree/main/library-book-search" },
  { slug: "localdata-business-status", name: "Localdata Business Status", category: "교통", url: "https://github.com/NomaDamas/k-skill/tree/main/localdata-business-status" },
  { slug: "lotto-results", name: "Lotto Results", category: "기타", url: "https://github.com/NomaDamas/k-skill/tree/main/lotto-results" },
  { slug: "market-kurly-search", name: "Market Kurly Search", category: "쇼핑", url: "https://github.com/NomaDamas/k-skill/tree/main/market-kurly-search" },
  { slug: "mfds-drug-safety", name: "Mfds Drug Safety", category: "기타", url: "https://github.com/NomaDamas/k-skill/tree/main/mfds-drug-safety" },
  { slug: "mfds-food-safety", name: "Mfds Food Safety", category: "기타", url: "https://github.com/NomaDamas/k-skill/tree/main/mfds-food-safety" },
  { slug: "myrealtrip-search", name: "Myrealtrip Search", category: "생활", url: "https://github.com/NomaDamas/k-skill/tree/main/myrealtrip-search" },
  { slug: "naming-house", name: "Naming House", category: "콘텐츠·검색", url: "https://github.com/NomaDamas/k-skill/tree/main/naming-house" },
  { slug: "national-pension-workplace", name: "National Pension Workplace", category: "공공서비스", url: "https://github.com/NomaDamas/k-skill/tree/main/national-pension-workplace" },
  { slug: "naver-ad-performance", name: "Naver Ad Performance", category: "기타", url: "https://github.com/NomaDamas/k-skill/tree/main/naver-ad-performance" },
  { slug: "naver-blog-research", name: "Naver Blog Research", category: "콘텐츠·검색", url: "https://github.com/NomaDamas/k-skill/tree/main/naver-blog-research" },
  { slug: "naver-news-search", name: "Naver News Search", category: "콘텐츠·검색", url: "https://github.com/NomaDamas/k-skill/tree/main/naver-news-search" },
  { slug: "naver-shopping-search", name: "Naver Shopping Search", category: "콘텐츠·검색", url: "https://github.com/NomaDamas/k-skill/tree/main/naver-shopping-search" },
  { slug: "nhis-care-checkup-search", name: "Nhis Care Checkup Search", category: "공공서비스", url: "https://github.com/NomaDamas/k-skill/tree/main/nhis-care-checkup-search" },
  { slug: "nts-business-registration", name: "Nts Business Registration", category: "교통", url: "https://github.com/NomaDamas/k-skill/tree/main/nts-business-registration" },
  { slug: "nts-tax-delinquency", name: "Nts Tax Delinquency", category: "공공서비스", url: "https://github.com/NomaDamas/k-skill/tree/main/nts-tax-delinquency" },
  { slug: "ohou-today-deal", name: "Ohou Today Deal", category: "쇼핑", url: "https://github.com/NomaDamas/k-skill/tree/main/ohou-today-deal" },
  { slug: "olive-young-search", name: "Olive Young Search", category: "쇼핑", url: "https://github.com/NomaDamas/k-skill/tree/main/olive-young-search" },
  { slug: "parking-lot-search", name: "Parking Lot Search", category: "교통", url: "https://github.com/NomaDamas/k-skill/tree/main/parking-lot-search" },
  { slug: "popbill", name: "Popbill", category: "금융·비즈니스", url: "https://github.com/NomaDamas/k-skill/tree/main/popbill" },
  { slug: "public-restroom-nearby", name: "Public Restroom Nearby", category: "공공서비스", url: "https://github.com/NomaDamas/k-skill/tree/main/public-restroom-nearby" },
  { slug: "real-estate-search", name: "Real Estate Search", category: "생활", url: "https://github.com/NomaDamas/k-skill/tree/main/real-estate-search" },
  { slug: "rhwp-advanced", name: "Rhwp Advanced", category: "문서·개발", url: "https://github.com/NomaDamas/k-skill/tree/main/rhwp-advanced" },
  { slug: "rhwp-edit", name: "Rhwp Edit", category: "문서·개발", url: "https://github.com/NomaDamas/k-skill/tree/main/rhwp-edit" },
  { slug: "s2b-notice-search", name: "S2b Notice Search", category: "공공서비스", url: "https://github.com/NomaDamas/k-skill/tree/main/s2b-notice-search" },
  { slug: "saju-fortune", name: "Saju Fortune", category: "콘텐츠·검색", url: "https://github.com/NomaDamas/k-skill/tree/main/saju-fortune" },
  { slug: "saramin-talent-search", name: "Saramin Talent Search", category: "콘텐츠·검색", url: "https://github.com/NomaDamas/k-skill/tree/main/saramin-talent-search" },
  { slug: "seoul-bike", name: "Seoul Bike", category: "교통", url: "https://github.com/NomaDamas/k-skill/tree/main/seoul-bike" },
  { slug: "seoul-density", name: "Seoul Density", category: "기타", url: "https://github.com/NomaDamas/k-skill/tree/main/seoul-density" },
  { slug: "seoul-subway-arrival", name: "Seoul Subway Arrival", category: "교통", url: "https://github.com/NomaDamas/k-skill/tree/main/seoul-subway-arrival" },
  { slug: "seoul-weather-risk", name: "Seoul Weather Risk", category: "생활", url: "https://github.com/NomaDamas/k-skill/tree/main/seoul-weather-risk" },
  { slug: "sh-notice-search", name: "Sh Notice Search", category: "공공서비스", url: "https://github.com/NomaDamas/k-skill/tree/main/sh-notice-search" },
  { slug: "srt-booking", name: "Srt Booking", category: "교통", url: "https://github.com/NomaDamas/k-skill/tree/main/srt-booking" },
  { slug: "store-longevity-radar", name: "Store Longevity Radar", category: "생활", url: "https://github.com/NomaDamas/k-skill/tree/main/store-longevity-radar" },
  { slug: "subway-lost-property", name: "Subway Lost Property", category: "교통", url: "https://github.com/NomaDamas/k-skill/tree/main/subway-lost-property" },
  { slug: "ticket-availability", name: "Ticket Availability", category: "교통", url: "https://github.com/NomaDamas/k-skill/tree/main/ticket-availability" },
  { slug: "toss-investment", name: "Toss Investment", category: "금융·비즈니스", url: "https://github.com/NomaDamas/k-skill/tree/main/toss-investment" },
  { slug: "zipcode-search", name: "Zipcode Search", category: "생활", url: "https://github.com/NomaDamas/k-skill/tree/main/zipcode-search" },
]
