import { Home as HomeIcon } from "lucide-react";
import { Link } from "wouter";
import { siteNav } from "@/lib/siteNav";
import type { DesignSystemReference } from "@/lib/designSystems";

export function DesignSystemPreview({ system }: { system: DesignSystemReference }) { const kind = system.previewKind; return <div className={`design-system-preview preview-${kind}`} aria-label={`${system.name} 컴포넌트 미리보기`} aria-hidden="true"><div className="preview-component-toolbar"><span>{system.name}</span><i /><i /></div>{kind === "button" && <div className="preview-component-body"><span className="preview-button">Primary action</span><span className="preview-button is-quiet">Secondary</span></div>}{kind === "form" && <div className="preview-component-body"><label>Label<span className="preview-input">입력 예시</span></label><span className="preview-button">Continue</span></div>}{kind === "card" && <div className="preview-component-body"><article><span className="preview-component-icon">✦</span><div><strong>Component card</strong><small>Spacing · states · hierarchy</small></div><span className="preview-button preview-icon-button">↗</span></article></div>}{kind === "table" && <div className="preview-component-body"><div className="preview-table-row is-head"><span>Component</span><span>State</span></div><div className="preview-table-row"><span>Navigation</span><b>Ready</b></div><div className="preview-table-row"><span>Feedback</span><b>Review</b></div></div>}</div> }

export function PageFrame({ active, kicker, title, children }: { active: string; kicker: string; title: React.ReactNode; children: React.ReactNode }) {
  return <main className="site-shell inner-page"><header className="topbar"><Link className="brand" href="/"><span className="brand-stamp"><span className="stamp-slash">/</span><span className="stamp-main">AI<span>100</span></span><span className="stamp-caption">FIELD<br />GUIDE</span></span></Link><nav className="topnav" aria-label="주요 메뉴">{siteNav.map(([label, href]) => <Link key={href} className={active === href ? "active" : ""} href={href}>{label}</Link>)}</nav><div className="top-actions"><span className="updated">AI/100 FIELD GUIDE</span><Link className="icon-button" href="/" aria-label="홈으로 이동"><HomeIcon size={16} /></Link></div></header><section className="inner-hero"><div><span className="section-kicker">{kicker}</span><h1>{title}</h1></div><Link className="back-home" href="/"><HomeIcon size={15} /> 홈으로 돌아가기</Link></section>{children}<footer className="footer inner-footer"><div className="footer-brand">AI<span>/</span>100</div><p>작은 문제를 찾고, 알맞은 도구를 고르고, 실제 결과를 공유하세요.</p><span className="footer-meta">CURATED FIELD GUIDE · 2026</span></footer></main>;
}


