import { ArrowUpRight, ChevronRight, Sparkles } from "lucide-react";
import { Link } from "wouter";
import { PageFrame } from "./GuideShared";

export function PathPage() {
  const steps = [["01", "말로 정리하기", "ChatGPT·Claude로 문제와 사용자를 한 문장으로 적습니다."], ["02", "화면 그려보기", "Stitch·Canva·Figma로 첫 화면과 흐름을 확인합니다."], ["03", "작게 만들어 공개하기", "Replit·Lovable로 만들고 GitHub·Vercel로 공유합니다."], ["04", "실제 업무에 붙이기", "반복 메일·문서·데이터 작업 중 한 단계만 자동화합니다."], ["05", "사용자에게 검증받기", "방문자 행동과 피드백을 보고 다음 기능을 결정합니다."]];
  return <PageFrame active="/path" kicker="A SMALL PATH TO A REAL PROJECT" title={<>처음이라면,<br /><em>이 순서로.</em></>}><section className="path-page"><div className="path-page-lead"><Sparkles size={24} /><p>처음부터 거대한 서비스를 만들지 않습니다. 이해할 수 있는 작은 결과를 만들고, 공개하고, 다시 개선하는 순서입니다.</p></div><div className="vibe-source-note"><span>VIBE CODING / PRACTICAL USE</span><p>바이브코딩은 “코드를 대신 써주는 마법”보다, 문제를 말로 정리하고 AI와 계획·구현·테스트를 반복하는 작업 방식에 가깝습니다. 아래 활용방안은 <a href="https://wikidocs.net/338128" target="_blank" rel="noreferrer">함께해요 바이브 코딩</a>과 <a href="https://wikidocs.net/340811" target="_blank" rel="noreferrer">효과적인 프롬프트 작성법</a>의 내용을 실전 순서로 재구성한 것입니다.</p></div><div className="vibe-use-grid"><article><span>01 / 업무</span><h2>반복 업무를 작게 자동화</h2><p>메일 초안, 문서 요약, CSV 정리, 고객별 안내문처럼 사람이 매번 반복하는 한 단계를 골라 AI에게 맡깁니다. 처음부터 자동 발송하지 말고 초안 생성과 사람 검수부터 시작합니다.</p></article><article><span>02 / 웹앱</span><h2>아이디어를 화면으로 만들기</h2><p>문제·사용자·필요한 화면을 먼저 말한 뒤, AI에게 계획을 요청하고 작은 기능 하나만 구현합니다. Next.js·React·TypeScript·Tailwind 같은 기술 규칙을 스킬로 고정하면 결과가 덜 흔들립니다.</p></article><article><span>03 / AI·데이터</span><h2>분석·분류·보고서 만들기</h2><p>데이터 파일과 목표를 제공하고, AI가 전처리·분석·시각화·해석을 나눠 수행하게 합니다. 결과에는 사용한 기준과 한계를 함께 적어 사람이 검증할 수 있게 합니다.</p></article><article><span>04 / 배포·사업</span><h2>작게 공개하고 검증하기</h2><p>TODO 앱이나 API 서버처럼 작은 프로젝트를 배포하고, 실제 사용자의 반응을 확인한 뒤 기능을 늘립니다. GitHub·Vercel·Netlify·Firebase·MCP 연결은 필요한 순간에 하나씩 추가합니다.</p></article></div><div className="prompt-recipe"><span>프롬프트 5요소</span><strong>구체성 · 맥락 · 제약 · 역할 · 예시</strong><p>“요약해줘” 대신 “누구를 위한 자료인지, 어떤 형식과 길이인지, 반드시 포함할 항목과 제외할 항목은 무엇인지”를 함께 적으면 AI가 다음 행동을 더 정확히 선택할 수 있습니다.</p></div><div className="path-page-steps">{steps.map(([num, name, text]) => <article key={num}><span>{num}</span><div><h2>{name}</h2><p>{text}</p></div><ChevronRight size={19} /></article>)}</div><div className="path-page-cta"><Link className="primary-action" href="/">도구 조합 다시 찾기 <ArrowUpRight size={16} /></Link></div></section></PageFrame>;
}

