import { useMemo, useState } from "react";
import { Check, Copy, Search, Sparkles } from "lucide-react";
import { workflowPrompts } from "@/lib/workflows";
import { PageFrame } from "./GuidePages";

export default function WorkflowsPage() {
  const [query, setQuery] = useState("");
  const [category, setCategory] = useState("전체");
  const [copied, setCopied] = useState<string | null>(null);
  const categories = ["전체", ...Array.from(new Set(workflowPrompts.map((item) => item.category)))];
  const filtered = useMemo(() => { const term = query.trim().toLowerCase(); return workflowPrompts.filter((item) => (category === "전체" || item.category === category) && (!term || [item.title, item.category, item.tools.join(" "), item.purpose].join(" ").toLowerCase().includes(term))); }, [query, category]);
  const copyPrompt = async (id: string, prompt: string) => { await navigator.clipboard?.writeText(prompt); setCopied(id); window.setTimeout(() => setCopied(null), 1600); };
  return <PageFrame active="/workflows" kicker="WORKFLOW PROMPT LAB / START HERE" title={<>어떤 일을<br /><em>하고 있나요?</em></>}><section className="workflow-lead"><div><span className="workflow-kicker"><Sparkles size={15} /> AI에게 일하는 법을 가르치기</span><p>도구 이름부터 고르지 말고, 먼저 하려는 일을 고르세요. 목적·배경·요청사항·제약·결과 형식을 채우면 AI가 더 정확하게 도와줍니다.</p></div><div className="workflow-stat"><strong>{workflowPrompts.length}</strong><span>실전 업무 프롬프트</span></div></section><section className="prompt-method"><div><span>01</span><strong>목적</strong><small>무엇을 이루려는가</small></div><i>→</i><div><span>02</span><strong>배경</strong><small>AI가 알아야 할 상황</small></div><i>→</i><div><span>03</span><strong>요청사항</strong><small>무엇을 해달라는가</small></div><i>→</i><div><span>04</span><strong>제약</strong><small>하지 말아야 할 것</small></div><i>→</i><div><span>05</span><strong>결과</strong><small>어떤 형태로 받을까</small></div></section><section className="workflow-browser"><div className="workflow-toolbar"><label className="ui-catalog-search"><Search size={18} /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="예: 메일 자동화, 웹앱, 인스타, 데이터…" aria-label="업무 프롬프트 검색" /></label><select value={category} onChange={(event) => setCategory(event.target.value)} aria-label="업무 카테고리 선택">{categories.map((item) => <option key={item}>{item}</option>)}</select><span className="workflow-count">{filtered.length}개 표시</span></div><div className="workflow-grid">{filtered.map((item) => { const prompt = `목적: ${item.purpose}\n배경: ${item.background}\n요청사항: ${item.request}\n제약: ${item.constraints}\n결과 형식: ${item.output}\n검수 기준: ${item.review}`; return <article className="workflow-card" key={item.id}><div className="workflow-card-head"><span className="workflow-index">{String(workflowPrompts.indexOf(item) + 1).padStart(2, "0")}</span><div><span className="workflow-category">{item.category}</span><h2>{item.title}</h2><p>{item.purpose}</p></div></div><div className="workflow-tools">{item.tools.map((tool) => <span key={tool}>{tool}</span>)}</div><div className="prompt-block"><div className="prompt-label"><span>복사해서 바로 써보세요</span><button onClick={() => copyPrompt(item.id, prompt)} aria-label={`${item.title} 프롬프트 복사`}>{copied === item.id ? <><Check size={14} /> 복사됨</> : <><Copy size={14} /> 복사</>}</button></div><p>{prompt}</p></div><details className="workflow-detail"><summary>왜 이 프롬프트가 똑똑하게 작동하나요?</summary><div className="workflow-detail-grid"><div><span>요청 예시</span><p>{item.request}</p></div><div><span>주의할 점</span><p>{item.caution}</p></div></div></details></article>; })}</div></section></PageFrame>;
}
