import { readFile, writeFile } from "node:fs/promises";

const sources = [
  { url: "https://www.mois.go.kr/gpms/view/jsp/rss/rss.jsp?ctxCd=1012", type: "news", organization: "행정안전부", domain: "mois.go.kr" },
  { url: "https://www.mois.go.kr/gpms/view/jsp/rss/rss.jsp?ctxCd=1001", type: "grant", organization: "행정안전부", domain: "mois.go.kr" },
];
const output = new URL("../client/src/lib/archiveFeed.ts", import.meta.url);
const strip = (value = "") => value.replace(/<[^>]*>/g, " ").replace(/<!\[CDATA\[|\]\]>/g, "").replace(/&amp;/g, "&").replace(/&nbsp;/g, " ").replace(/&#39;/g, "'").replace(/&quot;/g, '"').replace(/\s+/g, " ").trim();
const field = (block, name) => strip(block.match(new RegExp(`<${name}(?:\\s[^>]*)?>([\\s\\S]*?)</${name}>`, "i"))?.[1] ?? "");
const hash = async (value) => { const bytes = new TextEncoder().encode(value); const digest = await crypto.subtle.digest("SHA-256", bytes); return [...new Uint8Array(digest)].map((byte) => byte.toString(16).padStart(2, "0")).join(""); };
const existing = await readFile(output, "utf8").catch(() => "export const archiveFeed = [];\n");
const existingMatch = existing.match(/export const archiveFeed = (\[[\s\S]*\]);/);
const seedRecords = [
  { id: 1, type: "contest", title: "제14회 범정부 공공데이터·AI 활용 창업경진대회 통합공고", summary: "공공데이터와 인공지능을 활용한 아이디어 기획 및 제품·서비스 개발을 통해 공공데이터 기반 창업을 촉진하는 범정부 경진대회입니다.", organization: "행정안전부", sourceDomain: "mois.go.kr", sourceUrl: "https://www.mois.go.kr/frt/bbs/type013/commonSelectBoardArticle.do?bbsId=BBSMSTR_000000000006&nttId=125058", publishedAt: "2026-04-08T00:00:00Z" },
  { id: 2, type: "contest", title: "중소기업 AI 전환 우수사례 공모전 모집공고", summary: "중소기업의 AI 전환 우수사례를 발굴하고 공유하기 위한 공모전 모집공고입니다.", organization: "중소벤처기업부", sourceDomain: "mss.go.kr", sourceUrl: "https://www.mss.go.kr/site/smba/ex/bbs/View.do?cbIdx=310&bcIdx=1061253&parentSeq=1061253", publishedAt: "2025-08-28T00:00:00Z" },
  { id: 3, type: "exhibition", title: "2026 공공 AI 박람회(KPAIX)", summary: "공공 AI 솔루션·재해복구·AI 플랫폼과 클라우드·스타트업 기술 전시 및 포럼을 소개하는 공공 AI 박람회입니다.", organization: "행정안전부", sourceDomain: "mois.go.kr", sourceUrl: "https://www.mois.go.kr/frt/bbs/type010/commonSelectBoardArticle.do?bbsId=BBSMSTR_000000000008&nttId=127100", publishedAt: "2026-06-23T00:00:00Z" },
  { id: 4, type: "case-study", title: "(2026년) AI 정부 서비스 사례집", summary: "홍수예보·노동법 상담·복지 사각지대 발굴 등 공공부문 AI 활용 우수사례 16개를 소개합니다.", organization: "행정안전부·한국지능정보사회진흥원", sourceDomain: "mois.go.kr", sourceUrl: "https://www.mois.go.kr/frt/bbs/type001/commonSelectBoardArticle.do?bbsId=BBSMSTR_000000000015&nttId=124688", publishedAt: "2026-03-24T00:00:00Z" },
];
const parsedRecords = existingMatch ? JSON.parse(existingMatch[1]) : [];
const records = parsedRecords.length ? parsedRecords : seedRecords;
const byUrl = new Map(records.map((item) => [item.sourceUrl, item]));
for (const source of sources) {
  try {
    const response = await fetch(source.url, { headers: { "user-agent": "AI100-ArchiveBot/1.0" }, signal: AbortSignal.timeout(15000) });
    if (!response.ok) continue;
    const xml = await response.text();
    for (const match of xml.matchAll(/<item(?:\s[^>]*)?>([\s\S]*?)<\/item>/gi)) {
      const block = match[1] ?? "";
      const title = field(block, "title");
      const sourceUrl = field(block, "link");
      if (!title || !sourceUrl) continue;
      const summary = field(block, "description") || "공식 원문에서 자세한 내용을 확인하세요.";
      const publishedAt = field(block, "pubDate");
      byUrl.set(sourceUrl, { id: 0, type: source.type, title, summary, organization: source.organization, sourceDomain: source.domain, sourceUrl, publishedAt: publishedAt ? new Date(publishedAt).toISOString() : "" });
    }
  } catch (error) { console.warn(`[archive-refresh] skipped ${source.url}:`, error.message); }
}
const sorted = [...byUrl.values()].sort((a, b) => (b.publishedAt || "").localeCompare(a.publishedAt || "")).map((item, index) => ({ ...item, id: index + 1 }));
const content = `/* Generated by scripts/refresh-archive.mjs. Source links are preserved verbatim. */\nexport const archiveFeed = ${JSON.stringify(sorted, null, 2)} as const;\n`;
await writeFile(output, content);
console.log(`archive feed updated: ${sorted.length} records`);
